### ISSUE TITLE
"Cannot find config.php" after Upgrade on Subdomain Install

### ISSUE THREAD

**Issue by PopVeKind** [YOURLS/YOURLS#2332] opened 2017-12-05 00:12 UTC
I am running YOURLS in a subdirectory called **/s/**

After upgrading to the latest YOURLS files, I received an error, **_Cannot find config.php ..._**

If anyone else is having this problem on a subdomain install, you may want to look at Pull Request **#2331** to see if that fixes your problem.  **_It worked for me!_**

**Comment by LeoColomb** [comment] 2017-12-05 01:14
Yes, thanks @PopVeKind, we've seen your pull request.
Please don't duplicate issues and pull requests. 😺

**Comment by LeoColomb** [comment] 2017-12-05 01:15
Duplicate of #2331

**Closed by LeoColomb** 2017-12-05 01:15 UTC

**Comment by PopVeKind** [comment] 2017-12-05 05:50
@LeoColomb - Thanks for the tip!  I am still learning how to use GitHub.  It seemed many of the PRs I.ve read here also had issues.  This was my very first ever PR, I won't do that again.  Thanks!

**Comment by dgw** [comment] 2017-12-05 13:09
@PopVeKind Usually that's because the issue came first, and it took a while for someone to get around to making the PR. Creating an issue after a PR to fix it is already open just makes noise. :)
