### ISSUE TITLE
Fatal Error concerning county code.

### ISSUE THREAD

**Issue by tgimagine** [YOURLS/YOURLS#2635] opened 2020-04-01 18:54 UTC
Very strange error I am getting with yourls.

Please see tgimagine.com/ozh

This is a default url that is not working in other states from me.  I live in Virginia, USA. It seems that any other state that uses my yourls is getting this error:

`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'country_code' cannot be null' in /home4/tygiles/public_html/includes/vendor/aura/sql/src/ExtendedPdo.php:748 Stack trace: #0 /home4/tygiles/public_html/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute() #1 /home4/tygiles/public_html/includes/vendor/aura/sql/src/ExtendedPdo.php(306): Aura\Sql\ExtendedPdo->perform('INSERT INTO `yo...', Array) #2 /home4/tygiles/public_html/includes/functions.php(897): Aura\Sql\ExtendedPdo->fetchAffected('INSERT INTO `yo...', Array) #3 /home4/tygiles/public_html/includes/functions.php(740): yourls_log_redirect('ozh') #4 /home4/tygiles/public_html/yourls-go.php(21): yourls_redirect_shorturl('http://ozh.org/', 'ozh') #5 /home4/tygiles/public_html/yourls-loader.php(37): require_once('/home4/tygiles/...') #6 {main} thrown in /home4/tygiles/public_html/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748`

I test this using VPN, but I have heard from people living in different states than I reporting the same error.  This website is being hosted through hostgator which is located in Texas, USA, But even when I VPN to dallas, I get the same error.  Please advise!  This yourls application works PERFECTLY for me when I am not on a VPN.  When I do VPN to Washington DC, the yourl works aswell.  I use ExpressVPN.  Washington DC server works, other servers do not.  I do not see any country code in config, and my time zone is correct anyway.  Please help!  Thank you!

Oh and if you are at a location that does get the error above, you can get to tgimagine.com/admin with no issue proving that yourls is installed v 1.7.4.  Thanks again!

**Comment by tgimagine** [comment] 2020-04-01 19:03
![vpn](https://user-images.githubusercontent.com/63015517/78175987-c3761b80-7429-11ea-8036-9caf856473b8.JPG)
 Screenshot of the issue.  This works fine when I am not using a VPN.  And I get complaints of my links not working from people in other states.

**Comment by LeoColomb** [comment] 2020-04-01 20:25
Closing as duplicate of #2526

**Closed by LeoColomb** 2020-04-01 20:25 UTC
Labels: bug
