### ISSUE TITLE
First character being removed from shortened URL

### ISSUE THREAD

**Issue by fscheps** [YOURLS/YOURLS#2513] opened 2019-02-27 09:59 UTC
**Describe the bug**
Hi there, I´ve just installed YOURLS through Softaculous version 1.7.3 sometimes the first character of the shortened URL is removed. I saw this being reported in the past but no solution was provided, so decided to report it again. 
I recorded a video with the reported first character being removed behavior:
https://www.dropbox.com/s/nmihh9xheun1amg/YourlsStrangeBehavior.mp4?dl=0

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- YOURLS version:
- Plugins enabled: None
Server version: 10.0.37-MariaDB-cll-lve - MariaDB Server 
cpsrvd 11.78.0.12
Database client version: libmysql - 5.1.73
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.2.7

Sorry if I am missing something, I am not a developer. Thank you!!!

**Comment by LeoColomb** [comment] 2019-02-27 10:04
Duplicate of #2316

**Closed by LeoColomb** 2019-02-27 10:04 UTC

**Comment by fscheps** [comment] 2019-02-27 10:22
Sorry and thank you.
