### ISSUE TITLE
More useful error messages

### ISSUE THREAD

**Issue by tomslominski** [YOURLS/YOURLS#1861] opened 2015-03-08 18:27 UTC
Hi. I've noticed that the public page in the master branch right now returns `$status` and `$message` variables which provide information about whether the shortening has succeeded or not. That's great, but in practise, for me anyway, it's not that useful. For example, when you successfully shorten a _new_ URL, you get something like `string(7) "success" string(45) "http://tomslominski.net/ewr added to database"`. 

However, if you submit an _existing_ long URL, you get something like `string(4) "fail" string(51) "http://tomslominski.net/ already exists in database"`. Depending on how you look at it, that could be a success, as a short URL for that particular long URL is available.

I think it would be more useful if a wider variety of errors was introduced (such as 'exists' for the above error, as it's not really a success nor a fail).

Furthermore, not all errors seem to be handled this way. For example, if you submit too many URLs, [this happens instead](https://www.dropbox.com/s/i3su1aj4r4pkjql/Screenshot%202015-03-08%2018.26.10.png?dl=0).

**Comment by LeoColomb** [comment] 2022-02-21 19:52
Closing as duplicate of #1676

**Closed by LeoColomb** 2022-02-21 19:52 UTC
Labels: enhancement, core, api
