### ISSUE TITLE
This problem can sometimes be caused by disabling or refusing to accept cookies.

### ISSUE THREAD

**Issue by arjahanifard** [YOURLS/YOURLS#2405] opened 2018-06-22 08:09 UTC
hi

**Comment by dgw** [comment] 2018-06-22 09:57
Closing until more details are added.

**Closed by dgw** 2018-06-22 09:57 UTC
Labels: invalid, question

**Comment by arjahanifard** [comment] 2018-07-12 11:40
install subdomain
url.linuxfedora.ir
But I get the following error
((This problem can sometimes be caused by disabling or refusing to accept cookies.))
https://pasteboard.co/Hu6GGui.png

**Comment by arjahanifard** [comment] 2018-07-12 11:43
@dgw

**Comment by dgw** [comment] 2018-07-12 11:58
http://url.linuxfedora.ir/admin/ works, so YOURLS is at least installed and configured that much.

The root of that domain is stuck in a 302 redirect loop to itself, which is why you see that error. This is usually a server configuration issue. I can't help you any more specifically without knowing more about your environment. For this issue, HTTP server (Apache or Nginx) and version would be a good start.

I don't know why you've :-1:'d my closing comment. There was literally no way that anyone could even try to help until you provided details of the problem, starting with a proper error message. ("This problem can sometimes be caused by disabling or refusing to accept cookies" is a hint for the user, not an error that the webmaster can act on. The real error is above that: "Firefox has detected that the server is redirecting the request for this address in a way that will never complete.")

----

@LeoColomb, where's majordome when we actually _want_ it to prompt for missing issue templates? :joy_cat:

**Comment by LeoColomb** [comment] 2018-07-13 10:10
@dgw Hu hu, sorry, majordome is still sleeping most of the time! 😄

@arjahanifard I have to second @dgw, you're a not providing any information, and you have cleaned out the issue template.
Please take a look at the [Contribution Guidelines](https://github.com/YOURLS/YOURLS/blob/master/.github/CONTRIBUTING.md), which will tell you exactly what your ticket has to contain in order to be processable.

**Comment by IcedOtaku** [comment] 2019-09-11 10:12
> Your `/admin/` works, so YOURLS is at least installed and configured that much.
> 
> The root of that domain is stuck in a 302 redirect loop to itself, which is why you see that error. This is usually a server configuration issue. I can't help you any more specifically without knowing more about your environment. For this issue, HTTP server (Apache or Nginx) and version would be a good start.
> 
> I don't know why you've 👎'd my closing comment. There was no way that anyone could even try to help until you provided details of the problem, starting with a proper error message. ("This problem can sometimes be caused by disabling or refusing to accept cookies" is a hint for the user, not an error that the webmaster can act on. The real error is above that: "Firefox has detected that the server is redirecting the request for this address in a way that will never complete.")
> 
> @LeoColomb, where's majordome when we actually _want_ it to prompt for missing issue templates? 😹

i have the same issue
here is my nginx conf

```server {
  # HTTPS over IPv4 & IPv6
  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/url.waitforaday.site/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/url.waitforaday.site/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot  

  # Server names
  server_name url.waitforaday.site;
  error_log   /var/log/nginx/url.waitforaday.site_error.log;

  # Root directory
  root /www/url;

  # Rewrites
  location / {
    index /yourls-loader.php;
    #try_files $uri $uri/ /yourls-loader.php$is_args$args;
  }

  # PHP engine
  location ~ \.php$ {
    include fastcgi.conf;
    # OR
    # include fastcgi_params;
    fastcgi_index index.php;
    fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
  }
}
server {
  if ($host = url.waitforaday.site) {
      return 301 https://$host$request_uri;
  } # managed by Certbot
	server_name url.waitforaday.site;
  listen 80;
  return 404; # managed by Certbot
}
```
