### ISSUE TITLE
Modifying the redirect target for an existing URL link

### ISSUE THREAD

**Issue by Auselan** [YOURLS/YOURLS#2295] opened 2017-09-17 22:33 UTC
Dear all,

Fresh installation of YOURLS 1.7.2 and very excited.

Installation was quick and easy, URL generation working perfectly.

Am I being stupid though - I can't seem to redirect my links.  When I Edit an item and change the "Original URL" field,  my shortened link still redirects me to the URL I generated the link from e.g.

I use this link http://www.tomnichols.com to generate this 'shortened' URL in my YOURLS database: http://p1-preview.agilityhoster.com/tomnichols.com/YOURLS-1.7.2/mainwebsite

I edited it so that the current field is http://www.ouh.nhs.uk/ and saved the item, but the shortened URL still points to tomnichols.com

What am I doing wrong?  I had assumed that I could use the Admin panel to control the redirection of the link, but even when I delete the item, I can still use the shortened URL and seem to find my way to the original link!

**Comment by LeoColomb** [comment] 2017-09-17 22:37
Duplicate of #1964, #1832, and many others. Please search before creating a new issue.

**Closed by LeoColomb** 2017-09-17 22:37 UTC
