### ISSUE TITLE
URL changed after shortening

### ISSUE THREAD

**Issue by smarx80** [YOURLS/YOURLS#2660] opened 2020-04-23 10:56 UTC
Hi,
I'm trying to shorten this URL: 
https://www.awin1.com/cread.php?awinaffid=334259&awinmid=10139&clickref=11994&platform=dl&ued=https%3A%2F%2Fwww.unieuro.it%2Fonline%2F%3Fq%3Dsony%2520dualShock%25204%26dFR%5BcategoryNames_it.lvl3%5D%5B0%5D%3DAccessori%2520Playstation%25204%26utm_medium%3Dtextlink_na%26utm_source%3Dnetworkawin%26utm_content%3Ddinamica_prospect_vvk143db75d570393179420%26utm_campaign%3DUnieuro_cross_multi_alwayson%26dedup%3Dawin%26dclid%3DCJLKycCR_ugCFU-iewod7ikOLw%23x%26awc%3D10139_1587630769_809134be633268216a08acaee6200c0b

but yourl seems to decode some chars:

https://www.awin1.com/cread.php?awinaffid=334259&awinmid=10139&clickref=11994&platform=dl&ued=https://www.unieuro.it/online/?q=sony dual%Shock 4&dFR[categoryNames_it.lvl3][0]=Accessori Playstation 4&utm_medium=textlink_na&utm_source=networkawin&utm_content=dinamica_prospect_vvk143db75d570393179420&utm_campaign=Unieuro_cross_multi_alwayson&dedup=awin&dclid=CJLKycCR_ugCFU-iewod7ikOLw#x&awc=10139_1587630769_809134be633268216a08acaee6200c0b

The problem is that this second URL is not working properly.
Can you investigate please? 
Thanks,
Simone.

**Comment by ozh** [comment] 2020-04-23 11:09
Duplicate of a gazillions duplicates.

**Closed by ozh** 2020-04-23 11:09 UTC
Labels: encoding
