### ISSUE TITLE
Flickr URLs changing when shortening

### ISSUE THREAD

**Issue by fncll** [YOURLS/YOURLS#1889] opened 2015-04-25 17:49 UTC
I'm running 1.7.1, stock but for having the "Allow Hyphens in Short URLs" plugin enabled. I'm having a strange problem: when I shorten flickr URLs that don't have custom usernames, one of the letters in the original URL is being made lowercase (and therefore doesn't work). I don't have that problem with other URLs. 

For instance, see the top arrow in the following screenshot. That 'n' is an 'N' when I paste it in (<https://www.flickr.com/photos/127405888@N08/>), but when I submit, the resulting URL in the database has the lowercase 'n' (<https://www.flickr.com/photos/127405888@n08/>). It's exceedingly strange.

![yourls-lowercase-problem jpb](https://cloud.githubusercontent.com/assets/1208889/7334000/29cc923e-eb30-11e4-8a75-796403216889.jpg)

I haven't experienced the issue with other URLS, such as the one indicated with the second arrow...it seems limited to these flickr URLs.

Further, if I try to edit the URL to make it upper-case again, I get an update error!

**Comment by LeoColomb** [comment] 2015-04-25 19:31
It seems reproducible on my side with 1.7.1, and not with 1.4.1.
I suspect a bug with the `@` character, because no problem without it.

**Comment by ozh** [comment] 2015-04-26 10:14
That's a funny one indeed. Any character after a `@` will be lowercased. https://www.google.com/search?q=@OMG -> https://www.google.com/search?q=@omg
I'm closing this issue (it's not related to Flickr) and opening a new one

**Closed by ozh** 2015-04-26 10:14 UTC
Labels: bug
