### ISSUE TITLE
Support for PHP8

### ISSUE THREAD

**Issue by lkuza2** [YOURLS/YOURLS#2832] opened 2021-02-11 21:06 UTC
Using PHP8 results in a 500 server error.  I enabled PHP logging but couldn't get any errors to print out.

Reverting to PHP7 fixes the issue.

**Comment by dgw** [comment] 2021-02-11 21:07
Duplicate of #2807.

**Closed by dgw** 2021-02-11 21:07 UTC

**Comment by lkuza2** [comment] 2021-02-11 21:08
> Duplicate of #2807.

Sorry, I am stupid and totally missed that while searching.

**Comment by dgw** [comment] 2021-02-11 21:12
It's OK. Just that you're willing to admit that you missed it is amazing. So is the fact that you even tried to search first! 😸
