### ISSUE TITLE
Error 404 on shrinked URLs

### ISSUE THREAD

**Issue by Nhoya** [YOURLS/YOURLS#2025] opened 2016-01-23 12:52 UTC
as described [here](https://github.com/YOURLS/YOURLS/issues/2022) i did all the fixes but no results, except this cURL error but i think is not related to this problem
~~~
DB driver: pdo
SELECT `option_name`, `option_value` FROM `yourls_options` WHERE 1=1
SELECT `option_value` FROM `yourls_options` WHERE `option_name` = 'active_plugins' LIMIT 1
cURL error 28: Resolving timed out after 3514 milliseconds (POST on https://api.yourls.org/core/version/1.0/)
UPDATE `yourls_options` SET `option_value` = 'O:8:\"stdClass\":4:{s:15:\"failed_attempts\";i:45;s:12:\"last_attempt\";i:1453496502;s:11:\"last_result\";s:0:\"\";s:15:\"version_checked\";s:5:\"1.7.1\";}' WHERE `option_name` = 'core_version_checks'
SELECT COUNT(keyword) as count, SUM(clicks) as sum FROM `yourls_url` WHERE 1=1 
SELECT * FROM `yourls_url` WHERE 1=1  ORDER BY `timestamp` desc LIMIT 0, 15;
~~~

**Comment by dgw** [comment] 2016-01-23 12:57
Duplicate of #2022 (and even references it). Please do not create duplicate discussions just because nobody has answered in 16 hours.

**Closed** 2016-01-23 18:55 UTC
