### ISSUE TITLE
v

### ISSUE THREAD

**Issue by matbe81** [YOURLS/YOURLS#3509] opened 2023-02-08 09:28 UTC
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.7.2

### Description

I get suddently the following message when trying to accesshttp://ccbe.link/admin while everything was working for months without any changes.

Warning: main(./includes/load-yourls.php) [[function.main](http://ccbe.link/admin/function.main)]: failed to open stream: No such file or directory in /home/filigran/ccbe.link/admin/index.php on line 3

Fatal error: main() [[function.require](http://ccbe.link/admin/function.require)]: Failed opening required './includes/load-yourls.php' (include_path='.:/usr/local/lib/php') in /home/filigran/ccbe.link/admin/index.php on line 3

### Expectation

Normal dashboard

### Reproduction steps

http://ccbe.link/admin

**Comment by dgw** [comment] 2023-02-08 09:56
Duplicate of #3510

**Closed by dgw** 2023-02-08 09:56 UTC
Labels: bug
