### ISSUE TITLE
enable tags

### ISSUE THREAD

**Issue by sathish1981** [YOURLS/YOURLS#2610] opened 2020-02-26 07:09 UTC
@ozh  - Is this possible to enable in current build? I have 1.7.7, but still cant find tagging option out of the box. 
Do you have any plans in bring it in next versions?

**Comment by LeoColomb** [comment] 2020-02-26 17:44
Thanks for your question @sathish1981.
But please keep conversation in only one place if another ticket covers the exact same question.

Closing as duplicate of #1922

**Closed by LeoColomb** 2020-02-26 17:44 UTC
Labels: enhancement
