### ISSUE TITLE
Not Compatible With PHP 8

### ISSUE THREAD

**Issue by s22-tech** [YOURLS/YOURLS#2807] opened 2020-12-26 18:21 UTC
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x] This request isn't a duplicate of an existing issue, opened or closed
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
Yourls dies under PHP 8 with multiple errors.  Tested with the latest build from github.

`Deprecated: Required parameter $ip follows optional parameter $title in /home/public_html/includes/functions-html.php on line 522`

`Deprecated: Required parameter $clicks follows optional parameter $title in /home/public_html/includes/functions-html.php on line 522`

`Deprecated: Required parameter $timestamp follows optional parameter $title in /home/public_html/includes/functions-html.php on line 522`

`Fatal error: Declaration of Aura\Sql\ExtendedPdo::query($statement) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in /home/public_html/includes/vendor/aura/sql/src/ExtendedPdo.php on line 796`

**Comment by dgw** [comment] 2020-12-26 22:34
I'm sure this is a legitimate report, but please add the rest of the issue template—in particular, YOURLS version, PHP version (not just '8'), HTTP server & version, OS.

**Comment by s22-tech** [comment] 2020-12-27 00:09
Sorry, but I’ve deleted it already.

Versions:
YOURLS = 1.7.9? - whatever the latest version was from GitHub on 2020-12-25
PHP = 8.0
Apache = 2.4.46
CentOS = 8.?

**Comment by dgw** [comment] 2020-12-27 00:22
The latest version from GitHub depends on whether you downloaded a release or a branch.

Anyway, I've already made a PR that should fix the deprecation warnings. The fatal error is from a vendored library, probably many of which should be updated by someone who has testing infrastructure set up (I'm tooled for Python, not PHP).

**Comment by s22-tech** [comment] 2020-12-27 00:35
FYI, I took a look on GitHub again and I had downloaded the master branch.

**Comment by koehn** [comment] 2020-12-30 14:45
I can confirm that the 1.7.9 release fails under PHP 8; glad to know that there's an effort in progress to be compatible.

Thanks for building and maintaining such a useful tool! 

# 👏

**Comment by dlrudie** [comment] 2021-01-21 18:45
Fatal error: Declaration of Aura\Sql\ExtendedPdo::query($statement) must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in /home/public_html/includes/vendor/aura/sql/src/ExtendedPdo.php on line 796

-----

Simple fix to get it working due to PHP 8.0 changes.

includes/vendor/aura/sql/src/ExtendedPdo.php, line 796
change to:
public function query($statement, ?int $fetchMode = null, ...$fetchModeArgs)

includes/Database/YDB.php, line 479
change to:
public function query($query, ?int $fetchMode = null, ...$fetchModeArgs) {

includes/vendor/aura/sql/src/ExtendedPdo.php, line 190
change to:
if ($this->pdo->inTransaction()) {
    $result = $this->pdo->commit();
}


There may be more instances but this was enough to get it working for me.

**Comment by s22-tech** [comment] 2021-01-21 22:01
Thanks, David.  That got it working for me, too.

**Comment by s22-tech** [comment] 2021-01-22 04:41
Found another problem:

Deprecated: Required parameter $ip follows optional parameter $title in /includes/functions-html.php on line 523

Deprecated: Required parameter $clicks follows optional parameter $title in /includes/functions-html.php on line 523

Deprecated: Required parameter $timestamp follows optional parameter $title in /includes/functions-html.php on line 523

**Comment by dlrudie** [comment] 2021-01-22 16:38
@s22-tech Those issues were fixed in previous comments. I only amended the remaining fix.

**Comment by Flameborn** [comment] 2021-01-29 05:22
Arch Linux Arm recently switched to PHP 8.0.1.

Using Git 78e15033c1353a8af0bfd98cdbf61077e5d30c86 and the modifications posted by @dlrudie, the issue seems to be fixed.

**Comment by slauber** [comment] 2021-01-30 13:52
Followed @dlrudie fixes, I now get to the admin page, but it displays a DB error there with a http 503 code:
![image](https://user-images.githubusercontent.com/4493211/106358084-3ed68100-630a-11eb-9b94-13c78e246973.png)
I'm using PostgresDB, did an upgrade to PHP8 on Ubuntu 18.04, php-pgsql is installed (see installed packages below, no changes to the database config).
```
php-bcmath/bionic,now 2:8.0+80~exp2+ubuntu18.04.1+deb.sury.org+1 all [installed]
php-common/bionic,now 2:80~exp2+ubuntu18.04.1+deb.sury.org+1 all [installed]
php-curl/bionic,now 2:8.0+80~exp2+ubuntu18.04.1+deb.sury.org+1 all [installed]
php-fpm/bionic,now 2:8.0+80~exp2+ubuntu18.04.1+deb.sury.org+1 all [installed]
php-gd/bionic,now 2:8.0+80~exp2+ubuntu18.04.1+deb.sury.org+1 all [installed]
php-json/bionic,now 2:8.0+80~exp2+ubuntu18.04.1+deb.sury.org+1 all [installed]
php-mbstring/bionic,now 2:8.0+80~exp2+ubuntu18.04.1+deb.sury.org+1 all [installed]
php-pear/bionic,now 1:1.10.12+submodules+notgz-1+ubuntu18.04.1+deb.sury.org+1 all [installed]
php-pgsql/bionic,now 2:8.0+80~exp2+ubuntu18.04.1+deb.sury.org+1 all [installed]
php-xml/bionic,now 2:8.0+80~exp2+ubuntu18.04.1+deb.sury.org+1 all [installed]
php-zip/bionic,now 2:8.0+80~exp2+ubuntu18.04.1+deb.sury.org+1 all [installed]
php8.0-bcmath/bionic,now 8.0.1-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php8.0-cli/bionic,now 8.0.1-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php8.0-common/bionic,now 8.0.1-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php8.0-curl/bionic,now 8.0.1-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php8.0-fpm/bionic,now 8.0.1-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php8.0-gd/bionic,now 8.0.1-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php8.0-mbstring/bionic,now 8.0.1-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php8.0-opcache/bionic,now 8.0.1-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php8.0-pgsql/bionic,now 8.0.1-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php8.0-readline/bionic,now 8.0.1-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php8.0-xml/bionic,now 8.0.1-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
php8.0-zip/bionic,now 8.0.1-1+ubuntu18.04.1+deb.sury.org+1 amd64 [installed,automatic]
```

**Closed** 2021-01-31 22:32 UTC
Labels: bug, the issue template is not a suggestion
