### ISSUE TITLE
New Plugin to Limit the Min/Max Characters for Custom Keyword

### ISSUE THREAD

**Issue by suryatanjung** [YOURLS/YOURLS#3711] opened 2024-01-26 08:02 UTC
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

Hello :)
I just created a new plugin to limit the minimum and maximum number of characters for custom keywords.

### Motivation

- I've noticed that making keywords too long defeats the purpose of a "URL Shortener".

> _"Then why did you add "Minimum Length"?"_

- Because sometimes owners have to reserve some short keywords for their personal needs.

### Describe the solution

Therefore, I created this simple plugin to solve the issue:

> **[YOURLS Limit Custom Keyword Length](https://github.com/suryatanjung/yourls-limit-custom-keyword-length)**

I hope this can be useful to anyone who needs it.
It would be great if it was also added to the list of awesome YOURLS plugins. Thank you.

**Comment by dgw** [comment] 2024-01-26 10:01
Duplicate of YOURLS/awesome#160

**Closed** 2024-01-26 10:01 UTC
Labels: duplicate, plugin
