### ISSUE TITLE
Links with encoded characters not saved correctly

### ISSUE THREAD

**Issue by Marty** [YOURLS/YOURLS#2778] opened 2020-10-26 12:49 UTC
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x] This request isn't a duplicate of an existing issue, opened or closed
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
Encoded characters in a URL get decoded when saving.
Also there seems to be different behaviour between initially saving and editing a link in terms of masking/encoding/decoding.

**To Reproduce**

- Shorten `https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fmeetup-join%2F19`
- click edit and see that the URL is now `https://teams.microsoft.com/dl/launcher/launcher.html?url=/_#/l/meetup-join/19`

The encoded symbols got replaced by their decoded values which in case of MS Teams corrupts the URL and results in an error page. (Note that the above link is not a complete/valid MS Teams link with which you can test.)

When I edit the link and change it again to the original value, I gets stored correctly and the link works as expected. 

**Expected behavior**
The URL should be stored as-is and not be processed.

**Actual behavior**
The URL is changed because characters get decoded.

**Versions**
1.7.9

**Comment by ozh** [comment] 2020-10-26 14:32
Duplicate of gazillion issues. See pinned issue on the issues page. Fixed in next release.

**Closed by ozh** 2020-10-26 14:32 UTC
Labels: bug
