### ISSUE TITLE
yourls shortens itself

### ISSUE THREAD

**Issue by tessus** [YOURLS/YOURLS#2007] opened 2015-12-21 18:36 UTC
I'm using the latest version of yourls (git master).

Let's say YOURLS runs on `http://x.y`

When you shorten the URL `http://x.y`, I don't get an error, but a shortened URL (which is now longer than the URL) in the form of `http://x.y/wheteverIsNext`.

**Comment by dgw** [comment] 2015-12-21 18:56
This doesn't sound like a bug. Of course it shortens the URL you give it. Broadly speaking, even if the shortened URL is actually longer than the original, the user might want to use it for click tracking or some other function provided by a plugin.

:closed_book:

**Comment by tessus** [comment] 2015-12-21 19:05
The fact that the shortened URL is longer than the input URL was only secondary information. Did you understand what the issue is about?

I don't think you understand the implications of shortening itself.
I can't use my own URL shortener in a Twitter app, because, if I wanted to tweet about my URL service and its URL, the URL of my shortening service is actually shortened. So instead of showing `http:/x.y` it shows `http://x.y/1etr3t3`.

**Comment by dgw** [comment] 2015-12-21 19:17
Yes, I did understand. That's why I said, "Of course it shortens the URL you give it."

Twitter is a bad example because every URL you tweet is already shortened through Twitter's `t.co` shortener. But the fact remains, YOURLS will shorten what it's given, and it's not a bug that that includes its own URL.

My guess is that @ozh will say this is [Possible with a Plugin](https://github.com/YOURLS/YOURLS/wiki/Possible-With-A-Plugin) and close it.

**Comment by tessus** [comment] 2015-12-21 19:30
According to your logic it would then also shorten an already shortened URL, because "it shortens the URL you give it". But it does not. You'll get an error, if you try to shorten an already shortened URL.

So either you can have one or the other. You can't have both at the same time, otherwise it's inconsistent and therefore a bug.

There is a set of rules that shortening services are supposed to follow. I can't recall the entire set, but one rule defintely states that it shall not shorten itself. I'm sure you can find it, if you google for it.

**Comment by LeoColomb** [comment] 2015-12-21 22:48
> According to your logic it would then also shorten an already shortened URL

Depending of your configuration, see "YOURLS_UNIQUE_URLS" parameter.

---

In fact, I don't really understand what's wrong in your case. Everything works well except when shortening the URL of the shortener, which is, you may admit, quite a strange behavior! :smile: 
That said, it's a good catch, and an interesting point, but not a real bug since it follow the logic of the shortener itself (i.e. get a new URL for a given URL).

> but one rule defintely states that it shall not shorten itself.

You may be right, at least in your case, but again, depending of what you want. Isn't it?
If yes, the final anser is what @dgw said:

> My guess is that @ozh will say this is Possible with a Plugin and close it.

(except that is @LeoColomb and not @ozh :laughing:)

**Closed by LeoColomb** 2015-12-21 22:48 UTC

**Comment by tessus** [comment] 2015-12-22 01:35
Hmm, I still don't understand your reasoning unless inconsistency is your reasoning.

The `YOURLS_UNIQUE_URLS` parameter allows you to have different short URLs to the same long URL. I was talking about shortening already shortened URLs. This is not possible, no matter if `YOURLS_UNIQUE_URLS` is set or not. (Mine is set to `true`, the default behavior.)
If you do not allow shortened URLs to be shortened, you should also not allow the short URL itself to be shortened. Don't you understand the inconsistency otherwise?

Fixing a bug or strange behavior via a plugin is the wrong approach.

You have stated yourself:

> In fact, I don't really understand what's wrong in your case. Everything works well except when shortening the URL of the shortener, which is, you may admit, quite a strange behavior! 

Exactly, this is strange behavior and should be fixed.

**Comment by ozh** [comment] 2015-12-22 16:55
The only thing YOURLS won't shorten is a short URL it has generated. All other URLs in the world are OK. I think that's consistent and that is the expected behavior.

**Comment by tessus** [comment] 2015-12-22 20:25
Well, I guess that's it then for me. I will have to write a plugin. Anyway, shortening itself really seems strange to me.
This means I will either have to write a plugin, turn off shortening when wanting my URL service address not shortened in the twitter client, or use the web twitter client.
In any case, happy holidays!

**Comment by tessus** [comment] 2015-12-22 21:49
@ozh can you give me a hint, which hook I should use for the plugin?

**Comment by ozh** [comment] 2015-12-23 12:08
Probably `shunt_add_new_link` and return something your twitter client expects, probably an array just as if the shortening was successul.

There's a plugin called ShortShort which forbids shortening some URLs, have a look at it, it may be an easier start

**Comment by tessus** [comment] 2015-12-23 16:49
Thanks for the info. This will definitely help. Cheers.
