### ISSUE TITLE
Allowing Duplicate Long URLs or Redirect Short URL to Another Short URL

### ISSUE THREAD

**Issue by jamiers99** [YOURLS/YOURLS#2360] opened 2018-01-20 22:55 UTC
* YOURLS version: 1.7.2
  * Plugins enabled: 404 Not Found, Allow Forward Slashes in Short URLs, Don't encode/decode
* PHP version: 5.6.30

Hi all,

I have searched using a couple terms and am coming up short.  Question:

I want to redirect a shortlink to another shortlink.  I know that this is kludgy.  I was able to do it in the past.  I have one in my current YOURLS listing.  I get the error "URL is a Short URL."  This would alleviate the issue above.  I have some published shortlinks that I would love to get rid of, but cannot because they are in printed copies.  I would like to redirect it to a shortlink that I update every once in a while and I don't want to have to update both of them.  I have many like this.

Is this possible?

Thanks.

**Comment by jamiers99** [comment] 2018-01-20 23:23
Close this.  I just realized that I closed tickets weren't being searched.  Apologize  #2186

**Comment by dgw** [comment] 2018-01-20 23:47
Closing as duplicate of #2186 as requested (in a now-deleted comment?)

**Closed by dgw** 2018-01-20 23:47 UTC
Labels: duplicate, question

**Comment by jamiers99** [comment] 2018-01-21 00:53
I actually had restated my question that didn't get answered.  Is there a way to reopen?

**Comment by dgw** [comment] 2018-01-21 01:35
Removing the duplicate label, but discussion can continue even if closed. If this turns out to be a YOURLS problem, it can be reopened as an issue. :)

I don't know a solution off the top of my head, though, and I'm on my phone on a bus with limited research abilities for now. Maybe I can come up with something later, or someone else will beat me to it.

**Comment by ozh** [comment] 2018-01-21 10:03
redirect a shortlink to another shortlink : by default and by design, this isn't possible (to avoid sho.rt/abc redirecting to sho.rt/def which redirects to sho.rt/abc for instance)

If you want to bypass this check, the following simple plugin should do :

```php
<?php
/*
Plugin Name: Short URL so what
Plugin URI: https://github.com/YOURLS/YOURLS/issues/2360
Description: Don't check if short URL is a short URL
Version: 0.1
Author: Ozh
Author URI: https://github.com/YOURLS/YOURLS/issues/2360
*/

yourls_add_filter( 'is_shorturl', 'yourls_return_false' );
```

HTH

**Comment by jamiers99** [comment] 2018-01-21 14:20
That was stupid easy.  Thank you.

**Comment by jamiers99** [comment] 2020-10-12 16:42
Is there anything that would have made this break?
YOURLS Version v 1.7.9
with the following plugins:
404 Not Found https://github.com/DRGli/404-redirect-YOURLS
Allow Forward Slashes in Short URLs http://williambargent.co.uk/
