### ISSUE TITLE
draw.io link is not encoded correctly

### ISSUE THREAD

**Issue by fribse** [YOURLS/YOURLS#2420] opened 2018-08-07 08:00 UTC
When I create a drawing in draw.io and wish to publish it, it creates a link of 3490 characters (more or less).
When I try to shorten it with yourls, I get an error when I try to open the link.

1. Go to 'draw.io'
2. Click on 'New... (network in my case)'
3. Create a network diagram.
4. Publish link -> Copy
5. Enter it in yourls
6. Click the yourls short link

It should just open a lightbox with the diagram, like when clicking on it directly, or if I shorten it with tinyurl.com

- YOURLS version: 1.72 (just downloaded zip update today).
  - Plugins enabled: "Allow Hyphens in Short URLs"
- PHP version: 5.6.36

This might be covered by the 'that fucking URL encoding problem', but as the URL is so incredebly long, I can't tell.

**Comment by dgw** [comment] 2018-08-07 08:19
I can't reproduce this. I'm not entirely sure how to control the length of the draw.io link, but cloning one of the network diagram templates got me ~2314 characters to dump into my own YOURLS instance (using nginx, running under PHP 5 like yours), and it redirects just fine.

You say you get "an error" trying to open the link, but neglected to provide the actual error message and/or description, so I don't really know what I'm looking for beyond _something_ that doesn't work. :sweat_smile:

**Comment by fribse** [comment] 2018-08-07 08:41
I see a host of errors depending on what hoops I try to jump through, the URL I'm trying to encode is this one:
`https://www.draw.io/?lightbox=1&highlight=0000ff&layers=1&nav=1&title=Home.html#R7VxNc6O4Fv0ts%2FCyKZD4XMZOu6er8lKZTs2b1ysXwbKtaYxcIMdJ%2F%2FqRQLKRBDFOwPH0S7IwCPFh3XPPPfdKeAQn66cvebxZ%2FYfMUToC9vxpBK9HAADb99kHb3muWhw7CquWZY7nou3QcI9%2FItlRtG7xHBVKR0pISvFGbUxIlqGEKm1xnpOd2m1BUvWum3iJjIb7JE7N1r%2FwnK5Eq2PbhwO%2FI7xciVuHnjjwECc%2FljnZZuJ%2BIwAX5V91eB3La4n%2BxSqek12tCX4ewUlOCK221k8TlPLBlcNWnTdtObp%2F7hxltNMJSRD7wcMiXMwhgPbiUwirSzzG6VYMxu9kjcTT0mc5QrsVpuh%2BEyd8f8dgMILjFV2nbM9hm%2BUQIH4Tm%2B3tvyXfScgaJ%2FIAzcmP%2FRDzExcko9N4jVMOnf%2BifB5nsWgWMHFcvo%2FTdEJSkpdPAxce%2F99fUB7JSMbOGD%2BinGJm3KsULzPWTMlGXlJ8oYZxE038XPRUaxLj%2BAWxUaH5M%2BsijrrCpALzMKp2dwf8RJHosqpBxwtcgVuB2eX%2Byge7sQ1humYzQtcwEJozRItdktMVWZIsTj8fWms2cjSz1AyJnjD9H2%2B2wkDsfi93A1fs3qEcswdGuTiZjWD%2BXJ3iyd3v9WP6CQo6%2FkaUPgtLx1tKWNPh6W8It1z5XAWNc3rFXZ01JGlcFPzpq%2BYpTuXjt9q1INs8EUMlnZedu0Sym%2B4YrmAwPq4vwiFHaUzxo8okTcYtT2VfIX6uddgQnNGiduU73nBAWeB7CsxA4KgOfrQ%2FfLF%2FaEcv9Wcb1RO33M0F6tm%2BrX7%2FatjFWRq%2B92PYDfKSQYeDvIJ37zjcWZCr4%2F0A%2F4tDvIFuB5guIN2iZ8SfDprqofoATev3roW7EfBTNgLjOX5km0u%2B%2Bcft1R3rdHt1Lw%2ByG9WON5ziw%2BguJ1%2B%2FykMPud5Zv4QGZoaRDd9cPy25yLISXCTEKlDOIlIhPmc7TFczBuoSWnUMz%2BNitQ%2B%2FWrC0oR9GgREsD1JFj8ugFkNv4geU3pECU0x4LH0glJJ1a5DtqAM6RH3wEra7R%2BkwdFWwgcCI0zA0w7TfQ5Q20ecZ6PuaMVtmiJrklqZM%2FaJqFEtkJCnZsiuP31GK9WQUx%2FZV8eTZ0LCKAxrUU2gPYBYPvBhahKqsDXHKnWK8l%2F6a%2FKwzdBUx5pLGRQ%2FWUjtuOp%2BudqWbdrSQDGgyuFXRye0Q0Rxfi2itIa1T2AFdhJZ0iqHDjuM4KuhcHw4lVoAZZqb4gQ0esCHPKafQNuUMcx6quTIq8M%2F4oezAB12IRdbbG4%2B8a9YSC%2FZNUFbFBJ2W13g%2BL6VQC2br8GqwaZurGL6%2Bz83F447q%2BW0TB3xiaPNswbyvNa3sQhaLAr1ZYXpDK0zVITv4478koWpNnuqOD3qXl10J3w0GTx2sMFRs6xyzLYO%2FDV2VbWHodDJxR9N1RUJ%2FJnb9M5mYPPzNy4DALllt1KbjpzmmP38bkyfWM%2FC45uio5k9T8a3CohojFZRHJX8l7wvrQ%2BafoCiDQK%2FGmYIyaJD5HjwZe2xXwK8l9keDs82pYcR3NaaxwcXGEmjSykCFiZNLcVDFmCMEQ8dSmdSEeiLaf9XDLOn3U%2BMIPXj1Ud%2B4LOILtaTGacikh6pvwDPoqkjVVcNo5vcQVDKTUnJjZxCiM7jI81ui5QBl%2B%2FDioqEBkMvEAjgTFsD5sHB5yuiCyUIBw2UoIBhpFTTn5clFKOV1c%2F8jikm%2FG4z8oZDpwotDZqloTp5cfA9wusMw1VvBCcMj4NQXcJzaX8ycXxyYJVko%2Bl9DN5PYKc6YVpbrqWxdZL9SIBsF6Zov6ClAvCugtcA5mtFHU9Z7IHInbBTGrPMcs8tp0yw9iGfoqIsl3Mi1PEM%2BB54pnz1PdnzTTJTzYalultIVqxuBc9rJnM4x7CSHDK%2FLtYb10Wwe%2F6Nm6zBjU97sqtgckBHLnQV%2B4ggZi%2Be5XlHKF1Ne8S8Npsk8AxZOSLbALIblFotePH%2BPacw%2BeDsj2uk3Zs3tenaLtmh2d%2FuFNzmA6fnp%2BObPb1ffrU227MG0rudoprUN08pste8MFjRRpVH3%2BJoQ5iFx5zoJ9nzP7rlQsiZztC5mcTafbVbMrQor4TNts7L9EmslPZQ25LJiuUgAeE3s3AAN2IPPg%2BGLGzVJ2DZfNGQ59uQ0qNWmypz%2F%2BQq4Zo3VVqOEXMw4QI21och6v80fLdY0idcGdHjlr%2B6Gtu9PJm8MDbUD%2Bxj%2BUlBvVBIaP0zKvyZ%2B8MPQGcP2IC%2Bbr5lKSMRjZRyejZSik1yG6I7kP3ghONnmmD7PknjNObcfnRdqRVJghhiJUYVHelht5A2%2BqqALj9R83YV%2BJ29%2F96oYcM%2FGJKfmmkDL5mTO1boqW19lrfZXc8fXsJH7wUb%2FGjbSwXNONnKHZyNRuTqh1nXJha46IbmXQT56IcoNlHno4%2F3tI4Uuvcpr91q17U%2BDuZ2yt7s0fmawKEkA2KB7FnYAm5JR1cskTW%2BftbJhX3Uana3WRRIja4kyxlCptWRMNWMJPHu0NC37a6QaXPP%2FnqhMh5Znrq5vpLIeEjT3DO%2FA%2FbpUdqaZ5nOygVlMVV3fnOP5cPLXODkM%2FPM5uVl5VY1qksCHUV9jVBA55zOq3xC3NSs2lM9bR98Y5w6V82aLNaQGeuZh26E9bchVDvXTVvzp5sekCMoifGHt8AL3Y9hIewEY%2BuaCMBBZgWnaXpbaD7%2FEw4pkGB4yKPcbbRvWyp%2BvJgpURx%2FubVv5NWt%2BfRNv9pMBR%2Bc4mOU35dr3apqDmWez4sxYWGl1mV9ymsPxtDf2YdM0h9%2FAxdLZ3lSeHFxFKy89dShPBo7qr5F3uYvVm35JQq55eu%2FV6trs2bESZaQLgp5LlF6nZH3CiaDzROv9F2Dbn4D%2FtiXoO0yTFWIxmOSlYNjMqqZfk258%2FQdC5G%2FJ1F%2B9th2Tbbweyo%2FeGVaMeyfxjco1QdiJat5ljXDDyrv%2BNURnQzatXOrFm8MPZz5hYlNmbfs1jN2UA%2FB7gIB%2Fab5sOQf%2FLSdDLdu9XH8GF%2BXPZp2lb3%2Fu642x%2Fy8P97Qlqk3Ft8E8vNOLhNVL1n%2FdXN12RsY3tEExLX8Owwk8%2B3N3iLzxTe2PAlMPBSagJhbyNdhBCkxs9%2FDjmFXWcfgJUvj5Hw%3D%3D`

**Comment by dgw** [comment] 2018-08-07 09:17
5799 characters, no issues on my install.

I really think you should state some of these errors, as it seems to be an issue with your particular environment, not YOURLS itself. (To that end, I'm closing the "issue", but we can still talk.)

**Comment by fribse** [comment] 2018-08-07 13:36
Well, the hoops are different settings in the publish, also trying to paste the original URL in a browser, and copy it from there to the shorten url field.

Chome error:
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

Firefox error:
String contains an invalid character

I've restored a backup of the files, and have recopied the files to upgrade it.
I've tried encoding two URL's, one work, the other doesnt'.


URL1: `https://www.draw.io/?lightbox=1&highlight=0000ff&layers=1&nav=1&title=Home.html#R7V1Lc6O4Fv4td+FlXCAhHsvY6fR0VaYr05k7c3vlIhjbmsbgApxH//orgWQjCWzZBuxMO1nECAGyzne+85LIAI6Xb59Tf7X4PZmG0QAY07cBvBsAAAzbJn9oy3vZYhqeW7bMUzxlbduGJ/wz5B1Z6xpPw0zomCdJlOOV2BgkcRwGudDmp2nyKnabJZH41JU/D5WGp8CP1Na/8TRfsFbTMLYnfgvxfMEe7SJ24tkPfszTZB2z5w0AnBU/5emlz+/F+mcLf5q8VprgpwEcp0mSl5+Wb+MwopPLp6287r7h7GbcaRjnWhcEjm87zzN3NoUAGrMbF5a3ePGjNZuM35JlyEabv/MZel3gPHxa+QE9fiUwGMDRIl9G5MgkH4spCOlDDHK0+Zb0IEiWOOAn8jT5sZlieuEsifN7f4kjCp2/wnTqxz5rZjAxLXqMo2icRElajAbOEP3d3JCfiZOYXDF6CdMcE+HeRngek+Y8WfFbsi9UM2+siV4bvlWa2Dx+Dsms5Ok76cLOWkykDPPQKw9ft/jxPNZlUYEOciyGW4bZ+ebOW7mRD0x09WKEliKgcEoQzQ6TNF8k8yT2o0/b1oqMTEksFUGGbzj/H20eug47/F4cOhY7fAxTTAYcpuxiMoPpe3kJ4offq+fkCwR0/BPm+TuTtL/OE9K0Hf1DQiVXjCvL/TS/papOGoLIzzI6+rL5Hkd8+I1yzZJ1GrCp4spLrp2HvJusGBZjMDqvO+GQhpGf4xeRSeqEW1xKvoL/XumwSnCcZ5U7P9KGLcocGwkwA44pKvje/nBnf9fwdvUnH8oRNzzNAuLVtiF+/3La2VUSvjdzqAV5x+ke8qiCeHM/3F1CnlXADw10PsxLON2rBArgTaBqRQmmEzCvS2iNo6nYpQGwIzKu0RS/kI9z+vGPr7ePpNPX2yd+kjyocr7mEht6j2ny5Qs/9ZzKneVbSKgjolzRj8u3OfWGhgHOgmSYhSkxHRn7O3nF+WJC0FcgoAq2qZ8tNnZSsmoGtF3PUaza1qeQDSioGLsH/zmMHpMM5zihRu85yfNk2WgNNQ22hnkGu2hX35y6hmhPHXeIFIsKXdWg2i3YUxV+SIHfl5gIMw5zlYaiiPipYTmNBTSCKFmTO4/O6DS1JBXTsEWxIAMqUjFBjZ/jGh2IBYGdRoD5f5UpjqhWjDZOuuQoVpm05PYpp1vWg7RUzqvaJ/ulXE81JcRNDzc2pRmxuB3aYXtMWzQ9qNH0aFkDoOMScaVo2SVSvArTNEXQWTbsyq0Aqp25x89k8oABKSPdQ85LFcwR5cklVQ4z/NN/LjrQSWduHemNRgN0R1p8Rr9BGJdGQeblJZ5OC6elAbNVeNXItElVFF3fRNFsuINqJFrHATcEbchgzHusaHmXZDbLwlOFBlHXvqCokBr6+EFCn8Ywp6r4nAza03Ndwrd6cPJdV5DtXj+fwN+Alsi20DW1RKwpOl0ktCdiyz6XiF2zexFX4zijQb7dy+nkiKxOcG4DV3ebhXCBnOzak1WQ+1vWzv6eu7O/mIXYbzCS539olhgYhSkdNEWP9ynOf/5nlLyRng6ijq5mDHlY7NjozZbyFdVkb6BZBpXZ8BpcHhDGOE49fqtRjFMTWyLJ79QgPHLI4NeQx3L75T+NPJZji+btfN7LoZQJVYLsLWWlFk7aSVC5CN5ek1MXxh/AFfij1+QU7MEp9kSnuJuA5xzeMA+DhcSG2bbzW+/VILvB6uxJYxzqnW1KijxdYkhFYLm/5+7qf6i3pQK2exN3MlovE5igJ2A2uPMd5NcseHFYKKxYNXV6UeQlROnd4OFQfoGeBBd3d/QH5aURh/ZnNWm9GrQyOs/uCsy2mgo+S+6ikdiYHW/NeT/OKzdrigmor/wSf7jgl0tCI65vhGPiw/LVZIbs/B7puCpJ/oqIZdfcf83gcIbTcJK/qO42Ap41Jl95RDpPMbmdVLpqwamFprhUxPKsGq/WQapXixDveJKkzKuk9CQlO5KWB/qUE9gvJz5leFmstKzOZv387xWbRhWseNhtttoiw+cHM/xGETJi47lb5DldSnpLvzS4D6YxGOIgiWeYUHM6JKRM42o/98kf2k6M4f03Is31cvI1XIeTx6+faZNJw8D70cN/v91+H67ieQuitZApidZQRMuDyLYDS1BHlUo+4kuQEA3xtfMXGNnIaDmBsUym4TKb+PF0sloQtcqGAa1eTor2S8xhnA4Mly+q5gsvAKpj5xpowBZ03u4+5zDYn6O8vIRjJxnH45xyqWRiuruD/j39Tw76a/KhT+v0ZUiaxv5SQRNN0lU107Dt8fhEa1E5sTHru+x8rXMhUca4+KmjDNt1zRFstvu8+Y44DgEbVkwRW8syMu/FYf6apD9ozjZYpzh/nwT+ktJwO66fBAbPqeEWvkxa4JYWVnVxYrtyi8Qt1qVwC/AO45Y9/U/nFuvKLR+GW2Qw9MotVucrw3j+8ICM41EpmnPkpHkeTmGuVjM5x7k7Uo7QYvGubk7RMndQ0uE5xXJCWkmQawVhj5H/TkRfqDowgH4wtQWUEBhVsx11W+gaOa+tdIvMScss8MPhPIwJD0XDOeGjCYnDydCiqOgvUadzR39bIiwZKsjR46sW4iyrh418J/LVZZVHBLrqqY57LBsc7Ha5Xu1z2nKjLDXhKvKKWqu7MsgxDAIduz8GUbOzolBVhrkK9RihAs/sT6i2jlMwWuMov8GxdmqWrkU7Mi9bk9BvlLUiVY1cfj0+amIZOVQyDNe4rwmuthndRrTLYMNJ5hRlgWz4ime4HRh50oZsaKtLT4E3dFQgtbKhwuvBvxBK1o3+xVEJl0ql27A2Dd8rz631TFrcMVO3CN/uaSOcYwCRguTt9S2GIa7COA/+alPK2FuhIShZFQvTyyINEchqQTk7G0blbf6VRRoTSW9bgHVFGrvGSnDFPEW5UXfBw1btLEdRO6AVEZxjextXTCFfATtR1kOde092J8zdOVW5vwlAq8GA04NlOHAtk2MK79Mwh3qb7C4ieV/3TpnetiIgrRzSmBK1tq/49BkYxg2wT9t48IrzYBESfypJC+dvNSmb/p3mwJZfvsPf01R9WYJhqtYAtZD6dsHFKTRhGVGhNV+QcxHbMfnCnPNodN3auFY02r0q9AF1ch7zb1Yy63l3wG4BAt2XyQ/VZwuCy9HnI/ZXtB+3aQtTzdK1rc9t7RX8tTQcSYugoWtoRnCt6LjWJtJyn/rfD7dftbHxLVyFfl68xsZ0kPFJHyQnbna/pgxbSBkCEZMmTwP1kjJEfQeGQ1Njj/p21cQhVcmOPcSa1GBJ9H0nF2xlh9aOHVRHJAuQmh2kRaY//6ozKr9GbanmvVoKXLQDRWQA3UVSLVSXnO73ZB76CgqILFG/zQ/0KlX7nJGirRUpPuD4R/ae6fuWj55l3oCjbf91CabmEsxiO8sEtEMrfFHcZumlupfIqtkmZrWxYaRnr+HjLOu2GwPRvr0EhMT3Puxb1r2n/8leBZ+ZK3VdqQvBs1EXfzfYlboU6rqY3W62CQ+irj39T6curcTNlbp+CeqSN7z0SF3gMqirEsnZUFgvcmN8pCq+3cUWPG0XWt3l1g6n0IrzlVE+EKPY1vniOPUfXyig+GiyeV5nxz1DQv+mPrCqEBn9D3DP5FYVchvxNkZnwGgHFsCVnJq6d4UYdWWBNpaXqGuM7j6N/9wFjl+u6nOSdOWF4pt3e3RR9SGH2386WPq/23/tCD/9Hw==`

URL2: 'https://www.draw.io/?lightbox=1&highlight=0000ff&nav=1&title=Home.html#R7V1bk6K6Fv4t58HHtiAhXB5be3pmqvpM9ZneZ%2B8zTxaNqNmDYAH2ZX79SSBRSIJGBbT3OPPQEsLFrG9965bEARwv3z6n%2Fmrx72QaRgNgTN8G8G4AADBsm%2FyhLe9li2l4btkyT%2FGUtW0bnvCvkHdkrWs8DbNaxzxJohyv6o1BEsdhkNfa%2FDRNXuvdZklUf%2BrKn4dSw1PgR3LrX3iaL1iraRjbE19CPF%2BwR7uInXj2g5%2FzNFnH7HkDAGfFv%2FL00uf3Yv2zhT9NXitN8NMAjtMkyctPy7dxGNHB5cNWXnffcHbz3mkY51oXBI5vO88zdzaFABqzGxeWt3jxozUbjC%2FJMmRvm7%2FzEXpd4Dx8WvkBPX4lMBjA0SJfRuTIJB%2BLIQjpQwxytPmW9CBIljjgJ%2FI0%2BbkZYnrhLInze3%2BJIwqdP8N06sc%2Ba2YwMS16jKNonERJWrwNnCH6f3NDfiZOYnLF6CVMc0yEexvheUya82TFb8m%2BkGLcWBO9NnyrNLFx%2FBySUcnTd9KFnbWYSBnmoVcevlbwYzisz6KCHeRYDLgMtPPNrbeCIx%2BY7NRyhJYkoXBKIM0OkzRfJPMk9qNP29aKkExBLhVJhm84%2Fx9tHroOO%2FxRHDoWO3wMU0xeOEzZxWQI0%2FfyEsQPf1TPiRfU4PF3mOfvTNT%2BOk9I0%2FbtHxIquuK9stxP81uq66QhiPwso29fNt%2FjiL9%2Bo2CzZJ0GbKi49pJr5yHvJmqGxSiMjutOPKRh5Of4pU4lKuEWl5Kv4L9XOqwSHOdZ5c6PtGELM8dGNZwBx6xr%2BN7%2BcGd%2F1%2FB29ScfyjdueJoF6lfbRv37l8POrhLwvRlDLcg7TveQRxXEm%2Fvh7hL2rAJ%2BaKDzYV7A6V4lkABvAlkrSjCdgHldQmt8m4phGgA7Iu81muIX8nFOP%2F7n2%2B0j6fTt9omfJA%2BqnFdcYkPvMU2%2BfuWnnlOxs3gLAXVElCv6cfk2p%2B7QMMBZkAyzMCW2I2N%2FJ684X0wI%2BgoEVME29bPFxlAKZs2Atus5klnbOhWiBQUVa%2FfgP4fRY5LhHCfU6j0neZ4sG82hpsXWsM9gF%2B3q21PXqBtUxx0iyaRCVzaodgv2VIYfkuD3NSbCjMNcpqEoIo5qWA5jAY0gStbkzqMzek0tScU0YV0syICyowMUfo5rdCAWBHYaAeYAVoY4olox2njpgqdYZdKS26ecblkP0lI5L2uf6JhyPdWUEDc93NiUZsTidmiH7THtuulBjaZHyxoAHZeIK0XLLpHkVZimWQedZcOu3Aog25l7%2FEwGDxiQMtI95LxUwRxRnlxQ5TDDv%2FznogMddObWkd5oNEB3pMVn9BuEcWkURF5e4um0cFoaMFuFl0KmTaoi6fomjGavO6iGoioOuCFoQwZj3mNFy7sks1kWnio0iLr2BesKqaGPHyT0aQxzqorPyaA9PdclfKsHJ991a7Ld6%2BcT%2BBvQqrMtdE0tEWuKThcJ7YnYss8lYtfsXsTVOM5okG%2F3cjo5IlMJzm3g6m6zEC4Qs117sgpif8va2d9zd%2FavZyH2G4zk%2BW%2BaJgZGYUoHTdHjfYrzX%2F8aJW%2Bkp4No6kIzhjwsdmz0Zkv51tVkb6BZBpXZ8BpcHhDGOI4av9UoxlHElkjwOzUIjxwy%2BDXksdx%2B%2BU8jj%2BXYdfN2Pu%2FlUMqEMkH2lrKSKyftJKhcBG%2BvyakL4w%2Fg1vij1%2BQU7MEp9upOcTcBzzm8YR4G1xIbZtvOr9qrQXaD1dmTxjjUO9uUFHm6xBCqwGJ%2Fz93V%2F1BvSwZs9ybuZLReJjBBT8BscOc7yK9Z8OKwUFixaur0osirFqV3g4dD%2BQV6Alzc3dEfFOdGHNqf1aT1atDS23l2V2C25VTwWXIXjcTG7HhrzvtxXrmpKCagvvJL%2FOE1v1wQGnF9IxwTH5ZPJzNE5%2FdIx1VK8ldELLrm%2FmsGhzOchpP8RXa3EfCsMfnKI9J5isnthNJVC04tNOtTRSzPUni1DpK9WoR4x5MkZV4lpScp0ZG0PNCnnMB%2BOfEhw8tiqmV1NNXjv1dsGlWw4mG32WqLDJ8fzPAbRciIvc%2FdIs%2FpXNJb%2BqXBfTCNwRAHSTzDhJrTISFlGlf7uU%2F%2B0HZiDO%2B%2FE2mul5Nv4TqcPH77TJtMGgbejx7%2B%2B%2F32x3AVz1sQrYVMQbSGJFoeRLYdWAIVVUr5iK9BQjTE185fYGQjo%2BUExjKZhsts4sfTyWpB1CobBrR6OSnaLzGHcTowXD6rmk%2B8AEjFzgpowBZ03u4%2B5zDYn6O8vIRjJxnH45xyoWRiuruD%2Fj39Tw76FfnQp3X6MiRNY38poYkm6aqaadj2eHyitaic2Jj1XXZe6VwIlDEu%2Fqkow3ZdcwSb7T5vviOOQ8BeK6aIVbKMyHtxmL8m6U%2Basw3WKc7fJ4G%2FpDTcjusngMFzFNzCp0nXuKWFWV2c2K7cInCLdSncArzDuGVP%2F9O5xbpyy4fhFhEMvXKL1fnMMJ4%2FPCDjeFSK5hw5aZ6Hk5ir1UzOce6OkCO0WLyrm1O0zB2UdHhOsRyQVhLkWkHYY%2BS%2FE9EXqg4MoB9MbQFVC4yq2Q7VGrpGzmsr3SJy0jIL%2FHA4D2PCQ9FwTvhoQuJw8mpRVPQXqNO5o%2F9bIiwRKsjR46sW4iyrh4V8J%2FLVZZVHanTVUx33WDY42O1yPeVz2nKjLDnhWucVuVZ3ZZBjGAQ6dn8MImdn60KVGeYq1GOECjyzP6HaOk7BaI2j%2FAbH2qlZOhftyLysIqHfKGtJqhq5fDU%2BFLGMGCoZhmvcK4KrbUa3Ee0i2HCSOUVZIBu%2B4hluB0aesCAb2vLUU%2BANHRlIrSyo8HrwL2ol60b%2F4qiES6XSbVibhh%2BV5yo9kxZXzKgm4ds9LYRzDFCnIHF5fYthiCsxzoO%2F2pQy9lZoCEpWxcT0skhDBLJaUM7OhlF5m39kkcZEwm4LUFWksRVWgivmKcqNugsetmpnOZLaAa2I4BzL27hi1vIVsBNlPdS590R3wtydUxX7mwC0Ggw4PViGA%2BcyOWZtPw1zqLfI7iKS96o9ZXpbioC0ckhjStTavuLTZ2AYN8A%2BbeHBK86DRUj8qSQtnL%2FVpGz6Z5oDW9x8h%2B%2FTVNsVypStAWoh9e2Ci1NowjJ1hdbcIOcilmPyiTnn0WjV3LhWNNq9KvQBdXIe829mMut5d8BuAQLdl8kP1WcLgsvR5yPWV7Qft2kLU87Sta3Pba0V%2FL00HAmToKFraEZwrei41iLScp36Xw%2B337Sx8T1chX5ebGNjOsj4pA%2BSExe7X1OGLaQMQR2TJk8D9ZIyRH0HhkNTY436dtbEIVXJjj1ERWqwJPq%2Bkwu2tEJrxwqqI5IFSM4O0iLTH3%2BqjMrvUVtS7KslwUU7UEQG0J0k1UJ1yel%2BTeahW1BAZNX12%2FxAW6na54wUba1I8QHHP7P3TN%2B3fPQs8wYcbfuvUzA1p2AWy1kmoB1a4ZPiNlMv5bVElmKZmNXGgpGevYaPM63bbgxE%2B%2FYSEKrv%2B7BvWvee%2Fid7FXxkrtR1pS4Ez0ZdfG%2BwK3VJ1HUxq91sEx5EXXv6n05dWombK3X9FtQlLnjpkbrAZVBXJZKzYW2%2ByI3xkar4dhdL8LRdaHmVWzucQivOV0b5QIxiW%2BeL4%2BQfvpBA8dFk87zOjnuGgP5NfWBVITL6E3DP5FYVchvxNkZnwGgHFsAVnBrVXiGGqizQxvQSeY7R3afxH7vA8dtVfU6SrjhRfLO3Ry9VH8UPASqMyRc%2FnhY%2F36BpfO7KbbiPtz%2F7ISTu%2BLN35yFl8UFCopLY5Ip5nuK3YUCGstyXph0kmIY499M1FeUBU2EC%2BF6xJ0FByw85EgpA%2B4IrZk7CzGbOQvuIIYfbnywtg%2BftD8PCT%2F8H`

**Comment by fribse** [comment] 2018-08-07 13:44
Hmm, somewhere things go wrong.
I've just tried it again, and now it works, I wonder if it's draw.io's URL thats just wrong somehow?
So now I have two working draw.io drawings links, and one not working...

**Comment by ozh** [comment] 2018-08-07 16:38
Most likely this isn't a matter of URL length (it's stored as `TEXT` thus can be 65,535 bytes long) but simply [that fucking URL encoding problem](https://github.com/YOURLS/YOURLS/issues?q=is%3Aissue+is%3Aopen+label%3A%22that+fucking+URL+encoding+problem%22) which everyone is aware about.

**Comment by dgw** [comment] 2018-08-07 16:49
I discarded length as a possibility already.

Those errors sound like there might be an issue with how `draw.io` is constructing the URLs. Maybe try contacting [their support](https://about.draw.io/support/) with a link that throws one of those errors and see what they say about it.

**Comment by fribse** [comment] 2018-08-08 04:58
Ok, so that's up in the air at the moment, a bit saddened that I had to send the URL via an "open" service, and not just use my own, but until it's solved I guess I have to do so.

**Comment by ozh** [comment] 2020-05-18 16:37
Closing: 2691 and associated PR will supersede

**Closed by ozh** 2020-05-18 16:37 UTC
Labels: encoding
