### ISSUE TITLE
Used to work - can no longer add edit short urls - nothing changed

### ISSUE THREAD

**Issue by Kiroteryn** [YOURLS/YOURLS#2102] opened 2016-05-31 08:16 UTC
I searched for other closed/open issues related, and they were closed without resolution: 
1. https://github.com/YOURLS/YOURLS/issues/1887
2. https://github.com/YOURLS/YOURLS/issues/2089
3. Hmm I thought I saw a 3rd one, but just about to run out the door, will edit later

Perhaps someone could offer some insight? I can confirm there was nothing in console, even with debug mode on (no CORS blocks or anything like that). 

I checked out the site to get things working or I wouldn't have been able to add/edit/view things to begin with :) I have about 3 pages of links. It started when I went to edit a link, then that's when I realized.. nothing works! Funny enough, you can still delete. **I can view and delete, but not edit or add.** Strange, right? 

**Issue 1887 (#1 link above) has the EXACT issue as me -- worked fine, suddenly doesn't work with same reproduced results.**

The last activity performed that I recall was adding "blog3" shorturl to a tumblr site. Doesn't seem too iregular : https://myblogtumblr.com/post/12345679/url-is-quite-long-with-dashes-like-this

I don't know if it was triggered by that or when I went to edit a random entry that's related to another social site - nothing special or no odd naming conventions or special chars.

There is one consistent thing I noticed: Every open issue, the same mod closed it blaming the hosting service: How about instead of closing this ticket, let's work together and find the solution, hm? This seems to be reproduced lately.

**Another thing to add that seems quite important:** I reinstalled using a new db, and seemed to work again. I curiously swapped back to the old DB to see if that would work. Everything was back AND I could add things **.. and a few days later, this issue reproduced identically: Can suddenly, randomly, no longer add/edit.**
### Technical details
- YOURLS version: Latest
- PHP version: 5.6
- Win10 with multiple stable browsers
### Reproducible Bug Summary
1. Install yourls and setup db
2. Run yourls successfully for a few weeks
3. Out of nowhere, I cannot change, add links. No changes at all. I almost wish I _did_ change something so I knew what caused this.

This is a bug because you can no longer add/edit urls  or you get a loading GIF that never goes away.

**Comment by chtaube** [comment] 2016-05-31 08:29
What server software are you running? Is it a Windows server running IIS?

**Comment by ozh** [comment] 2016-05-31 17:39
I assume that when you say "I cannot add or edit", you get an infinite loading gif. Check the AJAX error that's returned (using Chrome devtools or Firebug for Firefox)

**Comment by dylanh724** [comment] 2016-06-15 08:11
He said

> I can confirm there was nothing in console, even with debug mode on (no CORS blocks or anything like that)

So it appears there's no AJAX errors.

I had the same issue earlier -- out of the blue. I used the "WIP" branch and works lovely (and looks awesome) so far! Just dragged and dropped - nothing special

**Comment by jondaley** [comment] 2016-08-16 22:03
I have the same issue.  Except that I can still edit on Firefox, but just not on chrome.

I don't have an "endless spinner", but the class of the edit image is changed to .disabled, so the background color goes to gray, but no errors, and just doesn't do anything.

Switching to firefox works fine, so I would think that means that it has to be a bug on yourls side.

**Comment by jondaley** [comment] 2016-08-16 22:11
Weird.  I tried to edit various URLs a couple times today without success.  I edited on firefox successfully.  I went back to chrome, fail.

Then since other people were saying they couldn't add URLs either, so I tried that, and that worked fine on Chrome.

And then.... magically... editing started working again.

**Comment by Kiroteryn** [comment] 2016-08-17 01:26
Most definitely a yourls bug.

**Comment by dylanh724** [comment] 2016-08-17 02:07
I still get intermittent behavior myself. I posted a bug earlier by saying
it resolves randomly, but now it "unresolved" randomly.

**Comment by pmainder** [comment] 2016-09-27 16:58
Same grey background on several different browsers. Consistent across browsers.
I have 470 short links and when I click edit for a random sample, around half cannot be edited.
I can add or delete URLs.

**Comment by dylanh724** [comment] 2016-09-28 02:15
Anyone try a fork or beta version?

**Comment by jondaley** [comment] 2016-09-28 02:38
Haven't had any trouble since it started working back in August...

**Comment by chtaube** [comment] 2016-09-28 04:16
No trouble here, too. Yourls is working fine for years now. Running on self-administered FreeBSD machine with nginx/php-fpm and MariaDB.

I agree that errors aren't handled very well.

**Comment by samy2k01** [comment] 2017-01-26 10:56
Drop the www when accessing the admin page. 

Access admin via:
http://mysite.com/admin/

and not:
http://www.mysite.com/admin/

**Comment by Kiroteryn** [comment] 2017-01-26 11:40
That didn't fix

**Comment by dylanh724** [comment] 2017-03-24 05:30
Updated 3/24/2017 -- **Still can't edit with updated master:** 

![Image of infinite spinning]https://i.imgur.com/ux8Q6Lw.png)

**Comment by ozh** [comment] 2017-03-24 19:36
This issue is a mess of various topics. Closing.

@dylanh724 check the wiki

**Comment by dylanh724** [comment] 2017-03-24 20:17
Wtf? Or just close every major bug that YOU can't figure out. That's not really how GitHub works.

**Comment by ozh** [comment] 2017-03-24 20:42
Your last comment is covered in the wiki. Other entries in this issue deal with various topics, hence don't pinpoint a precise problem that could be investigated and fixed. I agree: that's not really how Github works.

**Comment by dylanh724** [comment] 2017-03-24 20:44
It's obviously broken, but you don't want others to know? I've followed your outdated wiki and surely the others have, too

**Comment by dylanh724** [comment] 2017-03-24 20:46
Everyone is explaining the exact same symptoms in the exact same place that's reproduced every session.

**Comment by pmainder** [comment] 2017-03-24 20:55
I am still seeing this issue, and it is consistent on my installation. Also, what I experience is the same as other posters on this thread. I wish I was more technical to try and help, but all I can do is record my experience and hope someone smarter than me can figure it out.

**Comment by dylanh724** [comment] 2017-03-24 21:02
I just saw this update and I am saddened the developer abandoned us when
the issue is still clearly unresolved.... I am detecting a "shame close"

**Comment by LeoColomb** [comment] 2017-03-24 21:20
@dylanh724 Please be respectful.
Don't forget that all members on this project maintain it on their free time. Your last comments don't help us to be focused on issue resolving at all…

If you still have the issur

**Closed by LeoColomb** 2017-03-24 21:20 UTC
Labels: admin panel, bug

**Comment by dylanh724** [comment] 2017-03-24 21:24
@LeoColomb if the issue is closed when there's people that still report this issue in the exact same fashion and its randomly closed, THAT is what doesn't help focus. No one will ever know it's still an issue. 

If he doesn't "want" to fix it, then at least keep the ticket open so people are aware and maybe someone else that knows the back end well will fix it, instead. 

Whatever I say, will say, or have said is 10000x more productive than closing tickets the way he does

**Comment by dylanh724** [comment] 2017-03-24 21:26
Don't want to fix it != resolved
