### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by 201821134066** [YOURLS/YOURLS#2570] opened 2019-10-24 04:08 UTC
installation failed
![未标题-1](https://user-images.githubusercontent.com/50545488/67452768-e15b7b00-f656-11e9-9431-a20b371d15ad.jpg)

**Comment by 201821134066** [comment] 2019-10-24 04:34
ok, solved by setting the database to utf8_general_ci

**Comment by dgw** [comment] 2019-10-24 06:17
Marking duplicate of #2307 et al.

**Closed by dgw** 2019-10-24 06:17 UTC
Labels: bug
