### ISSUE TITLE
After updating the old link title is in weird characters

### ISSUE THREAD

**Issue by bassel999** [YOURLS/YOURLS#2620] opened 2020-03-12 23:57 UTC
* [X] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [X] This request isn't a duplicate of an existing issue
* [X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [X] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
After updating to the new version, all the new url titles working fine (Arabic characters) but all the old one are in weird characters, when I go back the old version they work fine.

**To Reproduce**
add Arabic url to the old version then update

**Screenshots**
https://watannetwork.gyazo.com/83f5a3f08b01e0f1dcfa840d11e337de

**Versions**
v 1.7.6

**Comment by dgw** [comment] 2020-03-13 05:56
> when I go back the old version

_Which_ old version?

**Comment by bassel999** [comment] 2020-03-13 14:31
> > when I go back the old version
> 
> _Which_ old version?

v 1.7.2

**Comment by ozh** [comment] 2020-03-14 15:03
Maybe a cheap fix for this could a plugin to update all link descriptions (ie fetch all long URL, mark those missing as 404 to allow for deletion and update title accordingly when applicable)

**Comment by ozh** [comment] 2020-03-14 15:18
Pinging @joshp23, maybe his plugin https://github.com/joshp23/YOURLS-Update-30X is just what is needed

**Comment by bassel999** [comment] 2020-03-14 15:56
> Pinging @joshp23, maybe his plugin https://github.com/joshp23/YOURLS-Update-30X is just what is needed

The only problem that I'm not so advance with API :) and the plugin looks like it need api

**Comment by joshp23** [comment] 2020-03-15 04:39
> I'm not so advance with API :)

Well, the good news is that [getting started with curl](https://www.poftut.com/curl-post-data-terminal-examples/) to trigger an api call is pretty straightforward. 

The Update-30X plugin checks existing long urls for redirects, storing the final destination. It also provides a list of unreachable links in the return call, which was intended to make adding 404 management trivial. 

For title updating, you might take a look at this [title re-fetch](https://github.com/joshp23/YOURLS-title-refetch) plugin I threw together.

If it's useful to you, I also make use of a [URL-Health Check](https://github.com/joshp23/YOURLS-URL-Health-Check) plugin which does what Update -30X does and more when links are initially submitted. It needs some work, particularly when determining reach-ability of links, but is reliable. 

I like the idea of working these into a unified link-management / housekeeping plugin, periodically addressing 30X and 40X errors, and cleaning titles with a cron job. But in the meantime the title refetch plugin would be my suggestion in this case.

**Comment by ozh** [comment] 2020-05-09 14:54
Anyone still following this discussion and having titles fucked up, and willing to try something?

**Comment by ozh** [comment] 2020-05-24 15:41
This problem finds roots in the fact that for a long time I didn't really pay attention to character set, being myself a `latin1` user. Apologies to all the Arabic, Chinese, etc.. friends with their funky character sets :) FWIW, the version of YOURLS I'm currently working on goes UTF8 all the way so this shouldn't be an issue ever again.

For people who have upgraded from an oldish YOURLS version (circa 1.7.2 / 1.7.3) the following might fix:

1. Find the date before which all your titles are borked, in Y/m/d format (eg "2016-10-16")
2. Run the following query (in something like phpMyAdmin) : 
```sql
UPDATE yourls_url SET 
    title=convert(cast(convert(title using  latin1) as binary) using utf8)
WHERE timestamp <= "2016-10-16"
```

Just to be sure, make a backup of your table before.

**Closed by ozh** 2020-05-24 15:41 UTC
Labels: bug

**Comment by ozh** [comment] 2020-05-27 09:08
(removed a couple comments to keep only solutions and pinning this issue)
