### ISSUE TITLE
Full fledged installer

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#1254] opened 2013-04-06 12:51 UTC
This is a **COPY** of **Issue 1254: [Full fledged installer](http://code.google.com/p/yourls/issues/detail?id=1254)**, filed on Google Code before the project was [moved on Github](https://github.com/ozh/google-issues-to-github).
- Submitted on 2012-12-10T17:32:01.000Z by [ozh...@gmail.com](http://code.google.com/u/113077239472542905682/)
- Status: Accepted

Please **review** the original issue and especially its comments. **Comments here on closed issues will be ignored**. Thanks.
## Original description

```
It would be neat to have a real installer with a web form instead of requiring users to manually edit the config.php

Copy "Famous WordPress 5 minutes install" (and make that "Famous YOURLS 4 minutes install", ah! beat that)

The installer should prompt for:
- YOURLS_DB_USER
- YOURLS_DB_PASS
- YOURLS_DB_NAME
- YOURLS_DB_HOST
- YOURLS_DB_PREFIX
- admin login / password

The installer should guess (and ask user if correct)
- YOURLS_SITE
- YOURLS_HOURS_OFFSET

The installer should generate
- YOURLS_COOKIEKEY

The installer should set default values for
- YOURLS_PRIVATE to true
- YOURLS_UNIQUE_URLS to true
- YOURLS_URL_CONVERT to 36 or 62? 62 seems to be the internet's default
- YOURLS_DEBUG to false
```

**Comment by PopVeKind** [comment] 2017-12-15 04:33
This looks like a worthwhile project to work on. A companion to the Diagnostic Page Project #2340 and pretty much in the same code blocks I am working in for #2335 and the six plugins I am committed to making described there.

Before I start the layout for this, I do have a few questions.  Likely these are things that have come up within the last 5+years.
## YOURLS_URL_CONVERT Default Value
Five years ago, from the above post...
- _YOURLS_URL_CONVERT to 36 or 62? 62 seems to be the internet's default_

From the current config-sample.php
```
/** URL shortening method: 36 or 62 */
define( 'YOURLS_URL_CONVERT', 36 );
/*
 * 36: generates all lowercase keywords (ie: 13jkm)
 * 62: generates mixed case keywords (ie: 13jKm or 13JKm)
 * Stick to one setting. It's best not to change after you've started creating links.
 */
```
From a recent issue #2333 ozh made this statement:

> Actually you CAN change from 36 to 62, because charset will expand.
> But if in the future you decide to change back from 62 to 36 things could go wrong

It seems that today the default value is now 36. **Is it 36?** Do you agree? Please comment?

**Comment by PopVeKind** [comment] 2017-12-15 05:59
# HTTPS

In the last couple years, HTTPS has exploded worldwide.   5 years ago (when this was proposed and accepted) no one thought about this. Today many YOURLS sites use some form of HTTPS.  We currently have settings for two purposes:
1. HTTPS in **Short Link URLs** - Something like `https://sho.rt/abc`
2. HTTPS in **Admin Link URLs** - Something like `https://sho.rt/admin/index.php`
## Single Menu Method
I think we should use **_ONE pulldown menu_** _(or a set of three radio buttons)_ on the install page, to make one of three selections:

Pulldown Choice | Short Link URLs | Admin Link URLs
------------ | ------------- | -------------
**HTTP in Everything** | HTTP | HTTP
**HTTPS in Admin Only** | HTTP | HTTPS
**HTTPS in Everything** | HTTPS | HTTPS

- _Note: HTTP in Admin Only (HTTPS in Short Link URLs | HTTP in Admin Link URLs)
makes no logical sense at all._

## Dual  Menu Method
Instead of using One Menu (above), we could use **Two Menus!**

Short Link URLs | []HTTP | []HTTPS
------------ | ------------- | -------------

Admin Link URLs | []HTTP | []HTTPS
------------ | ------------- | -------------


## What is your opinion?
Do you like the Single Menu Method better?
Do you like the Dual Menu Method better?
Please comment?

**Comment by PopVeKind** [comment] 2017-12-15 07:34
# YOURLS_SITE
YOURLS_SITE is the most widely misconfigured YOURLS constant.  In [This Post](https://github.com/YOURLS/YOURLS/issues/2244#issue-225795584) from #2244 ozh stated:
> For the record, roughly 4% (!!!) of YOURLS users misconfigure this variable with a trailing slash.

At this point in the installer, we have all the information needed to build the YOURLS_SITE constant.
## Is this a subdirectory site?
What is missing is the answer to one question, **_Is this a subdirectory site?_**

- **If YES** - YOURLS_SITE = YOURLS_ABSURL - which is already known.
- **If NO** - YOURLS_SITE = the protocol + http_host - which are already known.

The problem is... many noobs will not know what is meant by _Is this a subdirectory site?_
I think it is better to show them an example **_based on their website info._**
## Getting The Right Answer
**Is this a subdirectory site?**
_Choose The way your short links will look from these examples:_

Domain Root Site | Subdirectory Site
------------ | -------------
[] `https://cu.te/yourls` | [] `https://cu.te/y/yourls`

 


## What is your opinion?
Are examples better?
Please comment?

**Comment by ozh** [comment] 2017-12-15 22:01
Some answers

## YOURLS_URL_CONVERT

The problem as of today is that when you create a URL with a given charset, I'm not sure it's kept unchanged if then you change the charset.
Example:
    - pick charset 36 or 62 with a plugin to add `-` and `!` to the charset. Create shorturl `omg-!!`.
    - later, deactivate said plugin. While it should not be possible to create new short URLs with ! or -, I think short URL previously created should be preserved. Not sure it works like this at the moment, I think it's issue 2280

So, to answer your question, I think the default should be 36 (as of writing, 82.6% of YOURLS install use it), but that is kind of irrelevant since an installer should allow selecting either.

## HTTPS

I think this should *not* be part of the installer. The one think I don't want to end up with is an installer with a gazillion options to pick from. Since this does not depend on YOURLS but primarily on the server setup, I think YOURLS should not care about this.

For the record, as of writing, 89.9% of YOURLS install are on http instead of https. The truth is: the vast majority of people just don't care. It's a personal URL shortener, no sensitive data transmitted, it just works, period.

This said, I like your "one pulldown" concept, and I think that would make a neat plugin. That would even make a neat core plugin and we could deprecated a couple `YOURLS_` constants. That would really make a worthy PR to work on, and with it we could do our tiny part in promoting https.

## YOURLS_SITE

This is **far** from being the most misconfigured setting :) For the record, **47.9%** of YOURLS install have their locale defined as 'en_US', which is the default anyway and there's no translation file needed, I don't get why people would think they need to edit this setting to put a value that's not documented anywhere on the internet. Not "misconfiguration" per se, but just useless editing.

Back to your question: I don't think the installer would even need to ask the question. Drop files in some directory, load the installer in your browser: the URL itself gives a clue. The script should simply guess from the installer URL the path and URL of things.

## Conclusion

First, I appreciate your effort for readability and brevity, it's surely much more easy to read posts when they're shorter :)

Second, I don't think everything should end up in an installer. The less questions and options, the better. And then, plugins for misc things

**Comment by ozh** [comment] 2017-12-15 22:29
Heh. Knew it. Was wondering it the bot would ignore owners or members :)

**Comment by PopVeKind** [comment] 2017-12-16 12:22
# SUPER IMPORTANT!
I agree with your comment about guessing YOURLS_SITE with **_one caveat._**:
1. This means the **END** of hope for Multisite.

Multisite has been on the Roadmap for more than 5 years (I have six sites [different domains] working on a single Multisite Plugin now - with the YOURLS patch!) and I fully believe Multisite and other features are _impossible_ without splitting apart the two purposes YOURLS_SITE currently has.

I will provide you with **_PROOF_** of this.

## Single Site

Currently, YOURLS_SITE has two purposes:
1. The **_Site-URL_** purpose.  Making the Short URL links.
2. The **_Absolute-URL_** purpose.  Making the URL links to the _location_ of the YOURLS files, CSS, img, JS, etc..

YOURLS today, only allows **_a single site installation._**

- Therefore, **_in a single site_**, Site-URL = Absolute-URL and everything works fine **_for a single site only!_**
- As long as Absolute-URL = Site-URL, **_MultiSite is Impossible_**.
- I will prove this in the MultiSite post following this.

**Comment by PopVeKind** [comment] 2017-12-16 12:24
## Multisite

**_In this example_**, YOURLS files are physically loaded into the `/y/` directory - as in a subdirectory install.

_Note: a MultiSite with no subdirectory sites could be installed in any directory like_ `/yourls/`, `/peter/`, `/paul/`, _or_ `/mary/`

Site | Site-URL | Absolute = Site  | Needs Absolute-URL
-- | -- | -- | --
1st Site | `http://sho.rt/y` | `http://sho.rt/y` | `http://sho.rt/y`
2nd Site | `http://ti.ny` | `http://ti.ny` | `http://ti.ny/y`

1. The first example works fine.
2. The second example cannot work if Absolute-URL = Site-URL.
3. Absolute-URL needs to be a different value than Site-URL

The site installer cannot be written without knowing if it is a subdirectory or root install.  Not based on the files being located in the `/y/` directory.

In the last patch version, I solved this by defining YOURLS_SITE (Site-URL purpose) and YOURLS_ABSURL (Site-URL purpose) separately.

The new patch is written very differently:
1. $_SERVER elements are reduced to only those already used in YOURLS, plus one that is used daily in 75 million WordPress websites.
2. No additional constants are defined.
3. It will totally eliminate the trailing slash issue.

The next post is about Rejected PRs that are all common to this issue.

**Comment by PopVeKind** [comment] 2017-12-16 12:27
## Rejected PRs and YOURLS_SITE
Do a search in the PRs for YOURLS_SITE, it is eye-opening.  You will see quite a lot of Rejected PR features and fixes, where a part of the code deals with separating the Absolute-URL and Site-URL purposes of YOURLS_SITE.  All these PRs were rejected for adding a required constant to config.php

All these authors were correct, their feature could not be implemented in a Plugin because of YOURLS_SITE.

All the PR rejections were also correct, no required constants should be added to config.php

Most of these Feature PRs also have comments saying that the feature belongs in a plugin.  The authors reply they can see no way to make it into a plugin, and the PR is closed.

It is eye-opening how many PRs are rejected trying to deal with YOURLS_SITE problems.  Give me a week or two to finish the new patch for the YOURLS_SITE problems. (Remember it is Chrismas with lots to do with my kids, grandkids, and great-grandson!)  I think solving the YOURLS_SITE problems first, will make the YOURLS Installer much easier to code.

**Up Next**, a few replies to your comments and an idea to move most things into a global array we can store in the database.

**Comment by PopVeKind** [comment] 2017-12-16 12:29
**SUPER IMPORTANT!** (above) needs to be resolved before the installer.
## **YOURLS_URL_CONVERT**
Allow selection of 36 or 62, auto-select (suggest) 36.
Perhaps add a noob note: _"Most sites use 36. If you are new here, we recommend 36."_

### Two future ideas:
1. Allow all keywords in the DB to be considered valid. `HTTP://sho.rt/omg-!!` would check `omg-!!` against the DB even if it were currently considered invalid for building a new URL.
My current production project will require 3 sites and I plan to run them as 36 or 62. I don't see value in the complexity of other characters.  However, I do see value in a manually added two-word dash
`LP-Plan` or perhaps underscore like twitter `LP_Plan`

2. A clean-up plugin might be a good idea. It might allow currently illegal Short URLs to be modified. `omg-!!` could be edited to a currently valid keyword.

**Comment by PopVeKind** [comment] 2017-12-16 12:31
Please take time to study **SUPER IMPORTANT!** (above).
## HTTPS
My **first thought** for this was actually to create one global array, `$yourls`. `$yourls[ 'https' ]` would then be set to 1, 2, or 3.  This could originally be a single constant in config.php
`define( 'YOURLS_HTTPS', n );` Where n=1,2,3

However, if you asked me, I would create a settings page in Admin to change `$yourls[ 'https' ]` and then save `$yourls` in the database.

This would save a lot more than a couple constants.  There are functions that attempt to rewrite constants!
`yourls_site_url()` could be greatly reduced.
`yourls_get_relative_url()` might be eliminated altogether.
Many other functions could have improved performance.

**Comment by PopVeKind** [comment] 2017-12-16 12:36
**SUPER IMPORTANT!** (above) needs to be added to `$yourls`
# $yourls
Once `$yourls` is established, it would be easy moving other things into the database.
### $yourls[ 'hours_offset' ]
`define( 'YOURLS_HOURS_OFFSET', 0 );`
### $yourls[ 'lang' ]
`define( 'YOURLS_LANG', '' );`
### $yourls[ 'url_convert' ]
`define( 'YOURLS_URL_CONVERT', 36 );`
### $yourls[ 'passwords' ] (array)
```
$yourls_user_passwords = array(
	'username' => 'password',
	// 'username2' => 'password2',
	// You can have one or more 'login'=>'password' lines
	);
```
These could be added one at a time to `$yourls`.

**Comment by PopVeKind** [comment] 2017-12-16 12:55
## Last Thought
_It's time to sleep, but I had this one last thought._

In the future, when the settings page is working, we could have an installer that asked only for DB stuff and the first username/password.  Everything else could be set to defaults during the install and "customized" in the settings page - sorta like WordPress does.

**Comment by dgw** [comment] 2017-12-16 16:23
@PopVeKind Sending 7 separate comments (and therefore, 7 emails plus the bot reply) in the span of half an hour is much worse than writing one long comment… I know you're working on brevity, but splitting up your comments to avoid @majordome's length warning is not a good workaround 😂

**Comment by PopVeKind** [comment] 2017-12-17 01:07
Humm... @dgw I'm actually working on sub-topics or logical blocks like **YOURLS_URL_CONVERT**, **HTTPS**, and **$yourls**, that others may want to comment on.

On the other hand, I can see that the issue _Full fledged installer_ is not something everyone would want to follow.  For more than five years there were basically no comments until Leo brought it to my attention.  I think it is a great idea!  It will solve many problems. Any suggestions?

 Active Development, especially in the beginning of a project, requires many clarifications to reach consensus.  Comments from the community on these questions and suggestions are important.  I hope you and as many others as possible would comment.  Having different comments, with different titles, allows others to comment on different ones.  For example,

> _**About HTTPS**, suggest, suggest, suggest._

 If you are _not interested_ in a  _Full fledged installer_ you can take these steps to stop notifications:
1. Under your repository name, click Issues or Pull requests.
2. Choose an issue or pull request to unsubscribe from.
3. In the right sidebar (under `Notifications`), click Unsubscribe.

**Comment by PopVeKind** [comment] 2017-12-17 02:08
# LESS IS MORE
I think I made a mistake in the **_concept._** Ozh referenced the "Famous WordPress 5 minutes install"

WordPress does this by asking the **_required information_**, specifically the DB info and the first admin username/password pair.

1. The DB info goes into the config file.
2. The admin username/password goes into the database.

Beyond that, WordPress sets a bunch of benign settings in the database (changeable in the admin settings panel).  _Benign_ meaning install defaults that may be changed without problems at a later time.

## Stepped Approach
YOURLS could do the same thing in steps.
1. The installer would create everything as constants or global arrays in the config.php.  _**The same as now**, but automatic!_
2. One by one each setting constant is removed from the YOURLS code and placed into the DB, to populate the Global array $yourls. 
3. If a setting is missing from the DB, and therefore from $yourls, it falls back to the defined constants to **_make the setting in the DB!_**
Example, the bootstrap discovers `$yourls[ 'url_convert' ]` is empty.  If `YOURLS_URL_CONVERT` is defined this constant is used to establish `$yourls[ 'url_convert' ]` in the database.
4. After non DB constants are moved to the DB, config.php is reduced to the DB constants and any custom constants.  The other constants, like `YOURLS_URL_CONVERT`, are ignored, unused and may be deleted.
5. In the stepped approach, admin/user input/change is _**NOT Required** (the conversion is automatic)._

**Comment by PopVeKind** [comment] 2017-12-17 03:49
# New YOURLS Install
This is what I propose for the _"YOURLS **Fantastic Four** minute install!"_
```
REQUIRED CONSTANTS
These constants are put in the config file.

The installer should prompt for:
- YOURLS_DB_USER
- YOURLS_DB_PASS
- YOURLS_DB_NAME
- YOURLS_DB_HOST
- YOURLS_DB_PREFIX
The installer should generate
- YOURLS_COOKIEKEY

EVERYTHING ELSE
These constants - Initially put in the config file, then moved to the DB and $yourls

The installer should prompt for:
- admin login / password

The installer should set default values for
- YOURLS_HOURS_OFFSET to 0 (for GMT)
- YOURLS_LANG to en_US
- YOURLS_UNIQUE_URLS to true
- YOURLS_PRIVATE to true
- YOURLS_DEBUG to false
- YOURLS_URL_CONVERT to 36
- $yourls_reserved_URL - as currently defined in config-sample.php

RETIRING
- YOURLS_SITE by $yourls[ 'https' ] and $yourls[ 'http_host' ]
- YOURLS_ADMIN_SSL by $yourls[ 'https' ]
```

## What is your opinion?

Please comment?

**Comment by PopVeKind** [comment] 2017-12-22 05:26
The more I look at this, the more I realize the Installer needs to be built as an integral part of a number of programs.  These all hinge on the problems of using so many constants.

# Solution
To solve the problem, let's decide to remove all constants from the core files (except for the DB config).  Likewise, remove all config file constants, except for the DB and special constants used for plugins.
## Replacement
Obviously, we need a replacement.  I propose a static array in the Config class named **$yourls**.
## Careful Conversion
The conversion should be able to be performed one constant at a time.  This will increase focus on that one constant, producing less or no errors, reduced code bloat, and improved performance.
## Stored in Database
$yourls would be serialized and stored in the database.
## Programs needed
### Converter
This would convert config file constants into the $yourls array and then calls a DB class to save the $yourls array to the DB.  This should be written to be invisible to the user, and able to handle a single conversion so that this may be implemented one constant at a time. (Part of Config Class) Would only run if the $yourls element was empty.
### Installer
This is for new sites.  It builds the config file, the DB, and the $yourls array, and saves $yourls to the DB via the DB class. Would only run if config file could not be found and a required field from the DB was not available. (In other words Install runs only if the config file and the DB do not exist.
### Settings Page
This is a page in the admin area that allows setting changes to $yourls and saves $yourls to the DB vis the DB class.
### DB Class
This class (maybe _ExtendedPdo_) is used to update (including create) the DB with $yourls.  Also used to fetch $yourls from the DB on each access.
### Get $yourls
Gets $yourls from the DB (via the DB class) on normal loads. (Part of Config Class)
## $yourls
I think I have made the point that all this revolves around the **$yourls** static array.  And that each program is an integral part of the control and use of one static array, rather than a random hodgepodge of constants.

**Comment by PopVeKind** [comment] 2017-12-22 06:58
The **$yourls** static array is a possible improvement/solution for the following open issues.

#1254 #1284 #1344 #1354 #1611 #2244 #2280 #2281 #2335 #2343

**Comment by ozh** [comment] 2017-12-22 20:01
If you mean static as in ```static $some_array;``` then the answser is no : static variables mean they are not unit testable. See fc69856230920e49dd6d581789db0abc74ebbfda

**Comment by PopVeKind** [comment] 2017-12-24 00:12
@ozh - Instead of very rigid constants, or `public static $yourls` for the settings, how about just a `public $yourls`?  This would make things more flexible for a plugin writer.

**Comment by ozh** [comment] 2017-12-24 12:57
What do you mean "public" ? As for a [god object](https://en.wikipedia.org/wiki/God_object) that knows everything, we already have `$ydb`

**Comment by PopVeKind** [comment] 2017-12-27 04:53
# Core Options
This topic is all about **Core Options stored in the DB.**
## Class Config
Specifically, I was talking about defining a $yourls property within the Class Config.
`public $yourls`
~ ~ ~ vs ~ ~ ~
`public static $yourls`
## God Object
Defining a single property for a single purpose is hardly a **_god object._**
## Core Options
_Core Options_ (like `YOURLS_SITE` etc.) are currently stored in config.php as constants.  For many years a goal has been to move these _Core Options_ to the DB _" like WordPress."_
## The Options Table
The DB has an Options Table that has 5 rows.  The sixth could be named `core_options` and contain the **_Core Options Only_**, the serialized array of the **Config::$yourls** property.
1. A single property (**Config::$yourls**) for a single purpose (**The Core Options**).
## core_options
1. **Full Fledged Installer** would initialize the `core_options`
Once per site.
1. **The Config Tab** in the Admin Area would configure the `core_options`
Established sites would change this from never, to once every few years.
1. **Selected Not Typed** - For ease of configuration, if possible, `core_options` on the Config Tab will be selected, not typed.
1. **Optimize for Performance** -Eliminate Code Bloat, etc.
Before saving to the DB, the Config Tab would optimise the `core_options`
1. **The Config Class** would populate the $yourls array with `core_options`
Eliminates core option constants from config.php
1. **Config::$yourls** is available to any code that needs the `core_options`

**Comment by ozh** [comment] 2017-12-27 07:32
No singleton (`Someclass::someproperty`) because it's a unit test nightmare. If we move to something else than actually used, it would be dependency injection.

**Comment by PopVeKind** [comment] 2017-12-28 04:48
**No singleton - _Check!_**

I seem to be missing something like a YOURLS best practices for coding.  Can you give me a push in the right direction?  Maybe I missed that page?

So far I have collected this taboo list:
1. Don't add constants
1. Don't use a static array.
1. Don't use $_SERVER beyond what WordPress core uses.
1. No singleton (`Someclass::someproperty`)
1. Don't use the god object `$ydb` (**OR** maybe you meant I should use `$ydb`**???** - I'm not sure.)

**Could you give me a little direction** or at least some major check-points of how you want me to code this?

My idea goes along this line of thought:
1. Collect all core defined constants from `config.php` (except for the DB) together **_in one array._**  I would have called this array `$config` in the `Config` class, but this is already used so I called it `$yourls`.  This has all the manually configured user options.
1. Store this array in the DB. as `core_options` (done by either the full-fledged installer or changed in the admin section on a config page by selecting [clicking] options).
1. Retrieved from DB into `$yourls` in the `Config` class. (Fall back to `config.php` if not in DB.)
1. Use the `$yourls` array where the constants would have previous;y been used.

How would you suggest I use the `$yourls` config array from the `Config` class in the other parts of the code?

**Comment by PopVeKind** [comment] 2017-12-28 05:14
**_"we already have $ydb"_**

Maybe I'm just slow... Is `$ydb` being populated with everything from the database?

**Comment by ozh** [comment] 2018-01-07 10:02
Yes $ydb already gets populated with everything from the DB (hence the name). We don't want **another** god object.

**Comment by PopVeKind** [comment] 2018-04-08 03:41
# Switching Gears
After a few months of trying several approaches to building a full-fledged installer, my partner and I believe the key to this is removing the core options as constants on `config.php` and put them into the database.  We address our attempt to do that at **DB Config Page and Installer Project** #2380 

This includes an installer demo at:
[http://a.fil.net/s/admin/setup-config.php](http://a.fil.net/s/admin/setup-config.php)

By moving YOURLS core options to the database, they become available in **`$ydb`** as @ozh pointed out.  This greatly simplifies building a full-fledged installer.

A working demo of what a DB Config Page might look like within the Admin area can be seen at:
[http://a.fil.net/s/admin/db-config.php](http://a.fil.net/s/admin/db-config.php)

Please comment on these two demo pages at **DB Config Page and Installer Project** #2380

**Comment by ozh** [comment] 2018-04-08 19:28
Interesting stuff. I think the `?step=0` is totally unneeded, and there are way too many options in my opinion in the `db-config.php?language=en_US` page, though

**Comment by PopVeKind** [comment] 2018-04-09 01:46
Thanks, @ozh for your input. Here are short replies to your comments.
# `?step=0`
> I think the `?step=0` is totally unneeded

This page is totally unneeded! At least for people who already understand YOURLS and are capable of making an error-free config.php file! (Note: Experts may still fill out the config.php manually and go from there.) I included `?step=0` because WordPress includes it.  This is why it includes a "skip the rest of this instruction page" (for advanced/expert users), right after the list of required information.

**From the WordPress perspective** The `?step=0` page has three functions.
1. It provides instructions for noobs.
1. It is the very first page capable of having a .mo file translation.
1. It gives people time to gather necessary information for the entry page.

We can delete this page and `?step=-1` (the default page) and go straight to `?step=1` if we are to assume this full-fledged installer will only be used by English speaking YOURLS experts.
## Question?
Why are we making a Full-Fledged Installer if it is not for the purpose of helping Noobs?
# db-config.php
> there  are way too many options in my opinion in the `db-config.php?language=en_US` page, though

1. Let me make it clear that this page is **NOT** a part of the installer. It is only placed at the end of the installer **DEMO** (where the success page would normally be) to demonstrate which Core DB Options defaults were selected automatically by the installer.
1. As indicated by the menu, this page is added to the Admin area, a database replacement for `config.php` constants (except for DB constants).
1. The query `?language=en_US`is a coding error and will be removed.
1. If you turn on `View The Developer Notes` on this page you will notice (at the bottom) these 10 DB options replace and retire 10 Core Constants usually found in `config.php`
1. If `"there are way too many options"` then which options should be removed that are currently Core Constants in `config.php`?
## Question?
Does this mean we should abandon moving Core Constants from `config.php` into the DB?

**Comment by PopVeKind** [comment] 2018-04-11 23:52
# Subdirectory Installs
@ozh - **Do you have a percentage of sites that are loaded into a subdirectory?**  Something like `http://sho.rt/y`
# Too Many Options
### **`Delete ALL Core Options and Delete ALL Core Constants.`**
Ozh stated...
> there are way too many options in my opinion in the `db-config.php`

The 10 DB Core Options in `db-config.php` are performance improved versions of the 10 Core Constants (options) removed from config.php
Based on the information I have, these options are used by less than 15% of all sites. Meaning more than 85% of sites use the standard defaults.

Ozh also recommended moving the https/ssh option to a Core Plugin.

I was thinking, why not move **ALL** of these options to their own Core Plugin?
For example, a Time Zone Plugin and eliminate both `YOURLS_HOURS_OFFSET` and  `yourls_get_option( "timezone" );`
@LeoColomb @dgw @ozh - What do you think? Is it a good idea to remove **ALL** Core Options and **ALL** Core Constants and move each to a Core Plugin?

**Comment by PopVeKind** [comment] 2018-04-18 10:12
@ozh - Based on your comments I've uploaded the new version of the installer to:
### http://a.fil.net/s/admin/setup-config.php
### Please review it?


This version expects either one of the following two projects to be working.
Delete All Core Constants and Delete All Core Options #2388
Delete 10 Core Constants from config.php and add to Database, #2387

**Closed** 2020-04-08 14:31 UTC
Labels: enhancement, feature
