### ISSUE TITLE
shortened IDN URLs unable to open - stored wrong (with %) in database (Firefox)

### ISSUE THREAD

**Issue by Wolfus3** [YOURLS/YOURLS#1810] opened 2014-11-14 03:15 UTC
### Reproducible Bug Summary
1. Shorten any IDN URL, like www.tübingen.de 
2. output is: "http://t%c3%bcbingen.de added to database" 
3. open short link with Firefox (!) e.g.: http://siwik.de/go/s8z5 
4. Site-Loading error occurs (server not found), but URL is displayed correctly in address field. Must press ENTER, then website will be loaded. 
5. Bug only occurs (only?) with Firefox. Tested with Chrome and Opera - will work. Probably Chrome and Opera just opens everything what looks like a domain (well done,tho). 

This is a bug because...
The IDN could be stored "correctly" in the database, 
not http://t%c3%bcbingen.de 
but http://tübingen.de (or to be "safe" the resolved pendant xn--blah-b--.de) 

I installed the IDN plugin but this only seems to be useful if YOURLS is hosted ON AN IDN. But not for IDNs to be shortened. 
### Technical details
- YOURLS version: 1.7
- PHP version: 5.3.28
- MySQL 5.5.35 
- Firefox 33.1
- Opera 12.17 
- Chrome 38.0.2125.111 m 

....and by the way some credits to OZH for this/his great work.

**Comment by oyvind-lillegardsetre** [comment] 2015-03-05 13:04
Got the same issue in IE 11

**Comment by Alinya** [comment] 2015-03-12 00:51
Same issue with Firefox 36.0.1. The links work perfectly fine with Chrome though.
Also tested in Android Web browser, but the shortened link does not redirect to the long url properly either.
(Weird thing though is that it's a near-perfect copy of a working existing copy of a site running YOURLs, with only the relevant variables and values changed.)

**Comment by bmhm** [comment] 2015-03-13 08:42
Hey, I got issues with all browser and got my site hosted at µ.domain.de. Yourls fails all the time.

You need to open ./includes/functions.php and edit the function `yourls_get_request()` after $root being set:
    $root = idn_to_ascii($root);
    $serverhost = idn_to_ascii($_SERVER['HOST']);

    $request = str_replace($root . "/", '', $serverhost . $_SERVER['REQUEST_URI']);

I really don't like the coding style and the fact that I cannot use `idn_to_utf8()`. But this project seems abandoned. Shouldn't we fork it?

**Comment by ozh** [comment] 2015-03-25 13:15
Sure, go ahead :)

**Comment by aendrew** [comment] 2015-04-09 21:01
I have a similar issue; if I set the site URL as xn--6ca.ninja it [works](http://xn--6ca.ninja), and even http://æ.ninja/1 works, but if I set the site URL to æ.ninja, it redirects to front page. The only downside of using it the functional way is that it doesn't output the URL with the unicode character, so you have to manually replace the IDN value with the special character if you want the effect. Happy to PR this if it helps...

**Comment by ozh** [comment] 2015-04-09 21:23
@aendrew aren't you mixing up 2 things: shortening an IDN domain, and using YOURLS on an IDN domain ?

**Comment by aendrew** [comment] 2015-04-09 21:28
@ozh Oh! Indeed I am. Should I open a new issue?

**Comment by ozh** [comment] 2020-03-15 11:29
Closing this particular issue - duplicate of the well known funky char encoding issue

**Closed by ozh** 2020-03-15 11:29 UTC
Labels: duplicate, encoding
