### ISSUE TITLE
how to obfuscate the short links

### ISSUE THREAD

**Issue by verybigelephants** [YOURLS/YOURLS#2124] opened 2016-07-22 07:43 UTC
the yourls shortener is awesome and everything, but the links are very predictable. it's not hard to go guess other urls from domain.com/e, domain.com/f, etc. 

is it possible to work with some form of short hash like goo.gl, or bit.ly with yourls?

**Comment by dgw** [comment] 2016-07-22 07:44
Duplicate of #1946 (and others)

**Closed** 2016-07-22 07:54 UTC

**Comment by verybigelephants** [comment] 2016-07-25 13:24
i have searched A LOT before coming to post this. perhaps you should make it more visible in the official documentation

**Comment by ozh** [comment] 2016-08-07 16:40
Made it clearer in the readme.html because apparently people cannot read a readme or click on the first Google result.
