### ISSUE TITLE
%24 and %0A are changed upon storage

### ISSUE THREAD

**Issue by elduino** [YOURLS/YOURLS#2030] opened 2016-01-29 15:17 UTC
When, for example, the following link is shortened:
`http://www.falstad.com/circuit/circuitjs.html?cct=%24+13+0.000005+10.200277308269968+50+5+43%0Ar+624+208+752+208+0+4%0Ar+784+208+784+320+0+2%0Ar+816+320+944+320+0+3%0Av+592+320+592+208+0+0+40+20+0+0+0.5%0Av+944+208+944+320+0+0+40+10+0+0+0.5%0Aw+592+320+784+320+0%0Aw+784+320+816+320+0%0Aw+944+208+784+208+0%0Aw+784+208+752+208+0%0Aw+624+208+592+208+0%0A`

It results in the following redirect:
`http://www.falstad.com/circuit/circuitjs.html?cct=$+13+0.000005+10.200277308269968+50+5+43r+624+208+752+208+0+4r+784+208+784+320+0+2r+816+320+944+320+0+3v+592+320+592+208+0+0+40+20+0+0+0.5v+944+208+944+320+0+0+40+10+0+0+0.5w+592+320+784+320+0w+784+320+816+320+0w+944+208+784+208+0w+784+208+752+208+0w+624+208+592+208+0`

This changes the essence of the URL so it no longer works.

**Comment by ozh** [comment] 2016-01-29 22:07
Duplicate of a duplicate of a duplicate.

**Closed by ozh** 2016-01-29 22:07 UTC
