### ISSUE TITLE
Column 'country_code' cannot be null

### ISSUE THREAD

**Issue by xanathon** [YOURLS/YOURLS#2526] opened 2019-06-04 12:58 UTC
I get the feedback from some users that urls do not work and generate the following error:

`Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'country_code' cannot be null in /www/htdocs/w01882f8/pnde/includes/vendor/aura/sql/src/ExtendedPdo.php:748 Stack trace: #0 /www/htdocs/w01882f8/pnde/includes/vendor/aura/sql/src/ExtendedPdo.php(748): PDOStatement->execute() #1 /www/htdocs/w01882f8/pnde/includes/vendor/aura/sql/src/ExtendedPdo.php(306): Aura\Sql\ExtendedPdo->perform('INSERT INTO `yo...', Array) #2 /www/htdocs/w01882f8/pnde/includes/functions.php(897): Aura\Sql\ExtendedPdo->fetchAffected('INSERT INTO `yo...', Array) #3 /www/htdocs/w01882f8/pnde/includes/functions.php(740): yourls_log_redirect('o') #4 /www/htdocs/w01882f8/pnde/yourls-go.php(21): yourls_redirect_shorturl('https://phantan...', 'o') #5 /www/htdocs/w01882f8/pnde/yourls-loader.php(37): require_once('/www/htdocs/w01...') #6 {main} thrown in /www/htdocs/w01882f8/pnde/includes/vendor/aura/sql/src/ExtendedPdo.php on line 748`

This seems to be the case on iOs and Safari, but also on some instances of Firefox on Windows. Probably caused by some anti-tracking solution blocking the users country in some referral.

For most users this works, but I got multiple reports of this proiblem today for the url

http://pnde.eu/o

What can be the problem? Thanks in advance.

Edit: I see that Facebook crippled the error message, I will try to get a complete one and add it here.

**Comment by Ryfter** [comment] 2019-06-12 18:52
I just had a user tell me this, too.  It'd be nice to log this, and not have it spew it for anyone to see.  :-) 

What I was told: 

"Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'country_code' cannot be null"   

I'm running 1.7.3.

**Comment by ozh** [comment] 2019-06-12 19:42
Hi. First, we need to have a reproducible way to generate this error. Otherwise, we won't be able to check if a solution really fixes it.
I know it may be hard to pin point, but this is really the first step not to see an issue closed with "Works for me" :)

**Comment by spyjo** [comment] 2019-06-12 20:53
I already had the same problem, sometimes yourls_geo_ip_to_countrycode() is returning null or empty value, when the Maxmind db has no information on the user IP address. So the INSERT query in yourls_log_redirect() function is failing.

**Comment by xanathon** [comment] 2019-06-13 06:53
You guys are funny. How can I - in your opinion - reproduce an error that I do not get, but multiple users reported? Those are not techheads but simple users that just want a working link.

The error message seems to be somewhat helpful for me. The code tries to insert something into the column_country column but cannot. Since I do not know the code I can only presume that is to fill the statistics (that are probably not GDPR compliant anyway), but cannot, e.g. if the user has blocking mechanisms for such tracking.

"Works for me" is a quite bad answer form any support. As that does not address the problem and does not help the users in any way. There IS an error message that should at least give hints where to insert a workaround.

Thanks.

**Comment by Ryfter** [comment] 2019-06-13 07:04
I'm thinking what may be causing it, is the client isn't sending all the details, like country code for whatever reason. I'd be happy to pass the user through and not get the error but log it.  It blows up, and thst can be a security concern.

**Comment by ozh** [comment] 2019-06-14 20:47
@xanathon : just to clear something: ""Works for me" is a quite bad answer form any support." : there is no "support" provided. Volunteer free time as available, at best. This is free software with no guarantee of it working or it being fixed when someone encounters an error.

**Comment by xanathon** [comment] 2019-06-15 10:43
I'm totally clear how open software works. However, if you provide the possibility to report issues here on GitHub there should be someone who addresses those or do not offer the possibility and state so clearly on the YOURLS website. On that website the impression is given, that this is a somewhat professional endeavour and the use is encouraged with words one could see as advertising.

If there are gamebreaking errors and those are probably not addressed, the users need to know that before using the software so they can probably choose another solution. Changing to another solution after encountering errors is very cumbersome.

Thanks for your work.

**Comment by dgw** [comment] 2019-06-15 11:24
FWIW, in almost 8 years of using YOURLS (since long before I was invited to join the project), I have never seen this error. We ask for reproduction steps because we can't figure out how to trigger the bug ourselves—and without that knowledge, it is _very_ hard to even start working on a fix, because we can't test it.

**Comment by xanathon** [comment] 2019-06-15 18:55
As I said above. The error message was reported by multiple users on Win/Chrome, iOS and Mac OS. Those users are not tech-savvy enough to help. But they did provide that error message.

I do not know your code, but it seems obvious to me that some values cannot be inserted into a mySQL table because those are missing. To me it clearly looks like there are tracking countermeasures at work that lead to missing data like country of origin and that leads to an uncaught error. I can not know where you do such things (but I guess it is for statistics), so I have no idea where to look.

One way to relosve this could be to give admins the option to switch off statistics (besides clicks) as it is highly problematic due to gdpr anyway. ATM I have to change the code to prevent YOURLS to log IP addresses together with other statistics.

So: Yes, I know that it is difficult to find an error you can not reproduce, but it is there anyway - and there seem logical causes for this error that could lead to a solution. One of them could be to get rid of user statistics.

**Comment by ozh** [comment] 2019-06-15 20:57
No sweat. Most likely, the ip 2 country stuff has changed something on their end that causes `null` return. Probably all we need to do is make sure it always return something not `null`. Too bad we won't be able to check if that fixes the problem for those who encountered.

Next time someone gets a report from their user, please ask detail to them : their IP, the short URL requested.

**Comment by xanathon** [comment] 2019-06-24 13:46
We are not allowed to ask them their ip as by GDPR.

**Comment by LeoColomb** [comment] 2019-06-24 15:44
@xanathon You are allowed if the address is kept for a short time (i.e. not for mounts) and if your are not able to link their address with their personal data. (Disclaimer: IANAL)

You can totally get the IP for technical debugging! 🙂

**Comment by xanathon** [comment] 2019-06-24 19:23
I am able to link their IP address to their personal data and thus not allowed to give them to third parties. Believe me, I had to dig deeply into that GDPR shit for professional reasons last year. 

YORLS per se is not GDPR compliant without tweaks.

**Comment by LeoColomb** [comment] 2019-06-24 22:10
Ref: #2395

**Comment by OnlineBiblioTK** [comment] 2020-01-07 15:58
For example: 194.113.104.136
"Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'country_code' cannot be null"

Temporary SQL patch: 
ALTER TABLE `yourls_log` CHANGE `country_code` `country_code` CHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;

**Comment by OnlineBiblioTK** [comment] 2020-01-07 16:03
![image](https://user-images.githubusercontent.com/17561825/71909058-3dc33680-3180-11ea-96fc-55b76de5a3ba.png)
Country code really is NULL

**Comment by OranWeb** [comment] 2020-01-24 16:45
i found a way to reproduce this, 
see the URLs work fine on web/pc . but on mobile browsers especially samsung, oppo, vivo (which devices my users have reported) they don't work. but on chrome they do work, maybe the samsung etc devices are not sending the country code by default.

**Comment by tgimagine** [comment] 2020-04-01 19:11
![vpn](https://user-images.githubusercontent.com/63015517/78176366-5ca53200-742a-11ea-8d44-2f678674b28a.JPG)

I am getting this error for people using this URL who are not in my state.  I am in VA, USA and this works no problem.  In WV or Texas this is the error they get.  Try your self.  This error will populate, but tgimagine.com/admin works no problem.  Its just the yourls them selves.

Try tgimagine.com/ozh or tgimagine.com/yourls and see if thos work for you please.

If you have a VPN, try without it, and then try Washington DC.  DC works for my yourls, but other states do not.  I thought this may be something with the time zones, but West Virginia is on same time zone, and that state gets this error.  This affects yourls on PC and mobile for me.  It seems to triger depending where people are connecting from.  My yourls is hosted at hostgator in Texas, USA so that is why Dallas is strange for me.  Any ideas? I have multiple businesses relying on yourls.  Thank you!

**Comment by tgimagine** [comment] 2020-04-01 19:41
My public IP address on this VPN is 193.56.117.80 that is not working.  This is happening to all of my yourls instances that I have installed.  I am not sure how you were unable to get other reports of this.  I can get you as many links or errors as you want.  This is any browser for me, mobile or web.  I consider myself a "techhead" but not a deep level programmer.

**Comment by tgimagine** [comment] 2020-04-01 21:59
Closing as duplicate for a thread that has not been active in about a year?  Is that really a best practice?  Either way, I can give you examples for days, just let me know what you need.

**Comment by LeoColomb** [comment] 2020-04-01 22:02
@tgimagine This issue is still opened and active. Only the second issue you've opened (#2635) has been closed as duplicate of this one. But you're very welcome to continue the discussion here! 🙂

**Closed** 2020-04-08 15:40 UTC
Labels: bug

**Comment by iruga** [comment] 2020-11-06 13:34
I fixed this issue by updating includes/geo/GeoLite2-Country.mmdb to fresh one.
