### ISSUE TITLE
Core plugin "Allow Hyphens in Short URLs" should remove hyphens from random keywords

### ISSUE THREAD

**Issue by ozh** [YOURLS/YOURLS#2281] opened 2017-08-12 20:38 UTC
See https://github.com/YOURLS/random-keywords/issues/8

**Comment by TuKod** [comment] 2017-10-10 07:55
_Just some thoughts about this..._

**"Allow Hyphens in Short URLs"**

Why would a person want to do that?  I can think of two reasons...

1. **Random Keywords:** To increase the number of usable keywords.  for example, at just a 5 letter long keyword, there are  76,303,711 **_more_** keywords with the hyphen than without. **_76 million reasons!_**

2. **Custom Keywords:** To make custom URLs "pretty." Consider these two URLs and which you think is prettier?
http://fyuel.org/Pop-VeKind
 ~ ~ ~ vs ~ ~ ~
http://fyuel.org/PopVeKind

The Plugin's name is not "Allow Hyphens in **_Manually Entered_** Short URLs"

Some people will want hyphens in random keywords - just the way it is.

**Comment by PopVeKind** [comment] 2017-12-17 04:20
I just wanted to add this note here - I am pretty sure I will revisit this later.
# Two Possible Ideas:
1. **_Allow all keywords in the DB to be considered valid._** `HTTP://sho.rt/L-P-Plan!!` would check `L-P-Plan!!` against the DB even if it were currently considered invalid for building a new URL.

- I have a project with 6 sites and one with  3 sites. I plan to run them as 36 or 62. I personally don't see value in the complexity of other characters in my purpose.  But others might!
However, I do see value in a **manually** added two-word dash
`LP-Plan` or perhaps an underscore like twitter `LP_Plan`

2. **_A clean-up plugin_** might be a good idea too. It could allow currently illegal Short URLs to be modified.
`L-P-Plan!!` could be edited to a currently valid keyword.

**Comment by wci-aw** [comment] 2018-07-20 07:08
Hi,
I just cannot find out, it hypens "-" and underscore "_" is now allowed to be used in yourls short links.
Currently I have the hypens plugin activate and works with "-" but I also want to use underscore "_" too. How am I able to use both types in shorten YURL's ?
Best, Alex

**Comment by jools-r** [comment] 2020-05-01 10:44
I see this occasionally too when a hyphen happens to be randomly generated at the beginning or the end of the random url. I have allow hyphens in urls and allow slashes in urls installed for use with manually entered short urls.

Could this not be simply resolved by additionally restricting `$possible` in random-shorturls ([#35](https://github.com/YOURLS/YOURLS/blob/fd4b9278084ea558dbadd47d3c2b4db6e7aba040/user/plugins/random-shorturls/plugin.php#L35) to alphanumeric chars, either from the outset or stripping out the characters with preg_replace?

**Comment by LeoColomb** [comment] 2022-05-08 13:56
@ozh Reopening because of the following?

### Discussed in https://github.com/orgs/YOURLS/discussions/3328

<div type='discussions-op-text'>

<sup>Originally posted by **guigro** May  6, 2022</sup>
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9

### Description

For a few days, my shortener wasn't working.
It's all based on the acceptation of hyphens in my shortened link.


I updated, and it's still not working. 
If I don't activate the plugin "allow hyphens", it deletes the hyphens in my links, if I activate the plugin, i get a "YOURLS has nothing for you to see here."

I tried to deleted my database and reinstall the software, no change.

### Expectation

I was expecting my URL to be redirected correctly

### Reproduction steps

1. Install YOURLS
2. Activate Allow Hyphen plugin
3. Try to shorten an URL

### Context

_No response_</div>

**Comment by ozh** [comment] 2022-05-08 15:50
> @ozh Reopening because of the following?

Yes, this discussion reminded me that an old issue was still floating around

**Closed** 2022-05-29 12:18 UTC

**Comment by strarsis** [comment] 2022-07-22 21:57
The plugin for allowing hyphens isn't listed in the [curated YOURLS plugins list](https://github.com/YOURLS/awesome-yourls) and its page can't be found anymore.
Is this still supported somehow in latest YOURLS?
