### ISSUE TITLE
Redirecting and 403

### ISSUE THREAD

**Issue by amzens** [YOURLS/YOURLS#2268] opened 2017-07-18 15:22 UTC
Hello, i upload YOURLS to my server and i create .htaccess all everything is work if i put SHORT link is ok, but if i paste my SHORT link to forum i got this link (click right and copy) http://jeuxvideo.digidip.net/visit?url=https%3A%2F%2Fjeuxresources.site%2Fbleach-brave-souls-pool-resources-generator&ppref=https%3A%2F%2Fwww.google.com%2F redirecting me to https://jeuxresources.site/ how i can fix it? Please Help me.

**Comment by LeoColomb** [comment] 2017-07-18 23:10
Duplicate of #2269

**Closed by LeoColomb** 2017-07-18 23:10 UTC
