### ISSUE TITLE
Adding DeepLink Support

### ISSUE THREAD

**Issue by mrlufus** [YOURLS/YOURLS#3733] opened 2024-03-06 00:17 UTC
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [x] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

When interacting with Shorted Links on Social Media Apps (general use case), many people are nowadays on their phone and expect the link to open in the desired app. But Since Apps on Phones are Sandboxed, the Link isn't getting forwarded to the corresponding app therefore we need deep linking to solve this issue. 

### Motivation

Users are logged in on their social apps already.
When opening the Link in the Browser, potential new followers miss the opportunity to subscribe, since they don't wanna copy the topic of the link and open it in the desired app (e.g. a youtube link on instagram is getting opened in the instagram browser).

### Describe the solution

The Solution would be an option inside of YOURLS to toggle: "Deeplink" or "No Deeplink". 

If the toggle is set to "DeepLink" a deeplink script runs after, a available shorted URL gets resolved and trys to open up the app if available. If the App is not available on the phone, the fallback value would be resolving the original url (important for pc users).

In Addition to Deep Linking we run in a little Problem, which should also be faced. 
Previews and Descriptions of Videos are no longer displayed in Social Media Apps like Instagram, therefore we either need to copy and passthrough the Original Thumbnail and Description or just leave it blank

So far I can speak for "MANY" Content Creators around the globe which trust in YOURLs, since it's the only easy to use, plugin solution on the market. We all need this Solution, because this is the Dealbreaker Feature of Web 2.0 Services.

**Comment by dgw** [comment] 2024-03-06 00:44
Duplicate of #2504, and still plugin territory.

The wiki link referenced there has moved to https://yourls.org/docs/guide/extend/possible-with-a-plugin

As far as I can tell from searching our issues and discussions, this has been requested only twice in the past 5 years. Any feature that is to be implemented in YOURLS core must have *much* higher utility for the general user community.

**Closed** 2024-03-06 00:44 UTC
Labels: enhancement

**Comment by mrlufus** [comment] 2024-03-06 01:44
dgw You Closed this Case way to early in my opinion. 

Only because the most users are not "claiming" that they wish to have this plugin,
doesn't mean that their is no need for it.

But hey let's assume you are right and nobody needs to have it.

I can still gurantee you, that many people will appreciate this feature in the Future. 

Because Links nowadays are already as small as possible, the days in which links were 
tremendous so that you wanted to short them are mostly over. 

But having the opportunity to open links in their corresponding app, like an audible link (shorted) in audible. Because the amazon audible link can't deeplink into the app itself since it's not implemented in their service. Would make link rewrite- and shortening great again ;)

**Comment by dgw** [comment] 2024-03-06 02:07
If you assume I'm right that nobody needs to have this feature, how could you guarantee that many people will appreciate it? Users saying that they want something is the *only* way we have to prioritize and assess what gets added to the roadmap. If this feature was really in demand, our issues would be "noisier" about it. _(Insert old saying that "a squeaky wheel gets the grease".)_

You yourself described a need for fallback behavior, checking if an app is installed on the user's device and using the regular URL if it's not available. Implementing this would not be _simple_. It would add significant complexity to the application for little perceived benefit to the general userbase, and then the core team would also be responsible for maintaining it.

Speaking of maintenance, that's another reason this is better done in a plugin: A plugin can be updated whenever necessary to address changes in the mobile app world. A feature built into core would have to update in YOURLS' maintenance releases, which are pretty infrequent these days (as the core product is quite mature).

**Comment by mrlufus** [comment] 2024-03-06 02:38
Solid Point. Fully understand your thought.
Other Question, is it possible that we might get this as an official plugin?

Would be nice to have it here. (I've already tried to code it myself but wasn't successful yet)

**Comment by dgw** [comment] 2024-03-06 02:45
> is it possible that we might get this as an official plugin?

_Possible?_ Of course, almost anything is possible.
_Likely?_ No.

I personally don't have any interest in it. Another maintainer might, but I also think if one of them did we'd already have such an official plugin and you wouldn't have had to ask.
