### ISSUE TITLE
421 Misdiricted Request

### ISSUE THREAD

**Issue by Monschder** [YOURLS/YOURLS#2924] opened 2021-05-05 08:44 UTC
**Describe the bug**
421 Misdiricted Request when using YOURL on https with wildcard SSL

**To Reproduce**
Activate http2 on your Server
Use a SSL wildcard subdomain
Shorten to the first level domain

then:

1. The server and client both use HTTP/2.
2. The client requests a page at foo.example.com.
3. During TLS negotiation, the server presents a certificate which is valid for short.example.com and www.example.com (and the client accepts it). This could be done with a wildcard certificate.
4. The client reuses the connection to make a request for www.example.com.
5. The server is unable or unwilling to support cross-domain connection reuse (for example because you configured their SSL differently and Apache wants to force a TLS renegotiation), and serves HTTP 421.
6. The client does not automatically retry with a new connection. The relevant RfC says that the client MAY retry, not that it SHOULD or MUST. Failing to retry is not particularly user-friendly, but might be desirable for a debugging tool or HTTP library.

**Expected behavior**
Yourls routes to website

**Actual behavior**
Some Brosers show 421 Request failure

**Versions**
Actual version 1.8.1

**Additional context**
Is it possible to force a new connection before routing? An other option is to use an own certificate for every subdomain but it is sometimes not possible.

**Comment by LeoColomb** [comment] 2021-05-05 17:02
Thanks for opening this issue @Monschder.
That said I have some doubt that is caused by YOURLS itself, but most probably by the HTTP server (Apache httpd if I'm right).
YOURLS does not alter anything during TLS negotiation and only reply with a standard 301 or 302 when redirecting.

**Comment by ozh** [comment] 2021-05-05 19:12
I second @LeoColomb.

To further investigate:

* try accessing an existing non PHP file (eg short.example.com/readme.html). 
* try accessing an existing PHP file (eg make one at short.example.com/test.php that just `<?php echo "hello"; ?>`

These 2 cases will help you diagnose the problem (ie server misconfig or PHP problem). 

Closing as it's not YOURLS related, feel free to comment further on with more details if you think it is

**Closed by ozh** 2021-05-05 19:12 UTC
Labels: bug

**Comment by Monschder** [comment] 2021-05-05 19:23
No.@ozh
YOURLS works well. The Administration too.

And yes it is a apache problem.  The SSL with http2 opens only one channel for the communication. And one request. Cause of the wildcard certificate the request from the subdomain tried to reach the main domain with the same request - same url. This only happens in Safari, iOS and some browsers. The standard says browser "can" reconnect. Some do - some dont.

**Comment by Monschder** [comment] 2021-05-05 19:24
And its yourls related - in combinaton of http2 and wildcard SSL certificates.

**Comment by ozh** [comment] 2021-05-05 19:57
I don't get how it's YOURLS related then
