### ISSUE TITLE
Install trouble and short link not forwarding

### ISSUE THREAD

**Issue by migueldvasquez** [YOURLS/YOURLS#1965] opened 2015-10-06 01:07 UTC
My installation did not complete exactly as it was intended.  Consequently, the short-link redirecting is not working.

My install had the same issue as described here: https://github.com/YOURLS/YOURLS/issues/1617

I did a fresh install in the root directory using the latest Yourls version 1.7.

URL: cafund.org
Server: mysql.cafund.org or 208.97.162.120
Server version: 5.1.56-log
Protocol version: 10
Apache
MySQL client version: mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
PHP extension: mysql
PHP: 5.6 FastCGI

I get the installation error that has been reported on other cases:

Error creating table 'yourls_url'.
Error creating table 'yourls_options'.
Error creating table 'yourls_log'.
Error creating YOURLS tables.
File .htaccess successfully created/updated.

Yet the tables were created and the installation was complete.

My .htcaccess files was created and contained this:

# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
# END YOURLS

I added the following to prevent a breach in the config.php:
# BEGIN YOURLS
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ /yourls-loader.php [L]
</IfModule>
<files config.php>
   order allow,deny
   deny from all
</files>
# END YOURLS

I also successfully added the redirect-index and fallback URL plugins to redirect root page requests or bad links to http:/cafoundationfund.org.

The short link redirect problem still persists.

All short-links including http://cafund.org/ozh will be re-directed via the redirect-index plugin and not to the correct path, http://ozh.org/.

Let me know if you can help.

Thanks

**Comment by dgw** [comment] 2015-10-06 02:43
Duplicate of #1963. Please do not open duplicate tickets for the same problem.

**Comment by migueldvasquez** [comment] 2015-10-06 02:51
Sorry,

I though the other ticket was closed. 

I will wait a response for a fix.

**Comment by dgw** [comment] 2015-10-06 02:57
No worries. Closed tickets can still be commented on, and someone who knows more about Apache installations (I use nginx) can still try to help you on the other ticket. It's closed so it's not presented in the developers' ticket system reports as a defect that needs to be fixed, that's all. :)

**Closed** 2015-10-06 05:55 UTC
