### ISSUE TITLE
Public and Private Interface 

### ISSUE THREAD

**Issue by Yodale1000** [YOURLS/YOURLS#2292] opened 2017-09-09 14:28 UTC
So i just installed yourls and now i want to have a private install panel and a public interface but where do i have to move the sample-public-front-page . My English istn that good so plz help me

**Comment by dgw** [comment] 2017-09-09 18:51
Duplicate of #2291

**Comment by ozh** [comment] 2017-09-10 07:24
You don't "move" the sample, you customize it (copy the file, rename and edit) right where it is. Again, as Leo tipped, everything you need to know is in the wiki.

**Closed by ozh** 2017-09-10 07:24 UTC
