### ISSUE TITLE
Wrong redirection url with GET parameter containing encoded string

### ISSUE THREAD

**Issue by giaur500** [YOURLS/YOURLS#2618] opened 2020-03-11 12:04 UTC
For example, souce url:
http://domain.com?url=encodedUrl

Yourls makes redirection to invalid url, not properly encoded. So it's useless, because it redirects to wrong url actually

**Comment by ozh** [comment] 2020-03-11 20:32
Duplicate of a zillion issues.

**Closed by ozh** 2020-03-11 20:32 UTC
Labels: bug

**Comment by giaur500** [comment] 2020-03-15 07:18
Ok, but I am unable to get rid of that issue. Any advice please?

**Comment by ozh** [comment] 2020-03-15 11:16
For starters, a proper issue description.

**Comment by giaur500** [comment] 2020-03-15 15:28
What's not clear in description?
